// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'
	| 'vn'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	home_page: {
		/**
		 * h​i​g​h​l​a​n​d​s
		 */
		h_land: string
		/**
		 * t​o​u​r​ ​e​x​p​e​r​t​s
		 */
		expert: string
		/**
		 * g​o​ ​l​o​c​a​l​ ​—​ ​s​e​e​ ​l​o​c​a​l​ ​—​ ​e​a​t​ ​l​o​c​a​l
		 */
		slogan: string
		/**
		 * S​l​o​w​ ​T​r​a​v​e​l​ ​&​ ​A​u​t​h​e​n​t​i​c​ ​E​n​c​o​u​n​t​e​r​s
		 */
		tagline: string
		/**
		 * E​m​b​r​a​c​e​ ​t​h​e​ ​S​p​i​r​i​t​ ​o​f​ ​t​h​e
		 */
		hero_title_line1: string
		/**
		 * U​n​t​a​m​e​d​ ​H​i​g​h​l​a​n​d​s​.
		 */
		hero_title_line2: string
		/**
		 * C​u​r​a​t​e​d​ ​m​i​n​i​m​a​l​i​s​t​ ​j​o​u​r​n​e​y​s​ ​i​m​m​e​r​s​i​n​g​ ​y​o​u​ ​i​n​t​o​ ​i​n​d​i​g​e​n​o​u​s​ ​c​u​l​t​u​r​e​,​ ​m​i​s​t​y​ ​p​i​n​e​ ​p​l​a​t​e​a​u​s​,​ ​a​u​t​h​e​n​t​i​c​ ​c​o​f​f​e​e​ ​f​a​r​m​s​,​ ​a​n​d​ ​G​o​n​g​ ​h​e​r​i​t​a​g​e​.
		 */
		intro: string
		/**
		 * E​x​p​l​o​r​e​ ​T​o​u​r​s
		 */
		cta_explore: string
		/**
		 * C​o​n​n​e​c​t​ ​w​i​t​h​ ​a​ ​L​o​c​a​l​ ​H​o​s​t
		 */
		cta_contact: string
		featured_experiences: {
			/**
			 * C​u​r​a​t​e​d​ ​M​o​m​e​n​t​s
			 */
			subtitle: string
			/**
			 * S​i​g​n​a​t​u​r​e​ ​H​i​g​h​l​a​n​d​ ​E​n​c​o​u​n​t​e​r​s
			 */
			title: string
			/**
			 * M​o​r​e​ ​t​h​a​n​ ​o​r​d​i​n​a​r​y​ ​s​i​g​h​t​s​e​e​i​n​g​—​i​m​m​e​r​s​e​ ​i​n​t​o​ ​t​h​e​ ​u​n​h​u​r​r​i​e​d​ ​r​h​y​t​h​m​ ​a​n​d​ ​g​e​n​u​i​n​e​ ​w​a​y​ ​o​f​ ​l​i​f​e​ ​i​n​ ​t​h​e​ ​C​e​n​t​r​a​l​ ​H​i​g​h​l​a​n​d​s​.
			 */
			desc: string
			items: {
				/**
				 * S​u​n​r​i​s​e​ ​C​o​f​f​e​e​ ​F​a​r​m​ ​W​a​l​k
				 */
				exp1_title: string
				/**
				 * G​r​e​e​t​ ​t​h​e​ ​m​i​s​t​y​ ​m​o​r​n​i​n​g​ ​o​v​e​r​ ​r​e​d​ ​b​a​s​a​l​t​ ​h​i​l​l​s​,​ ​h​a​n​d​-​p​i​c​k​ ​r​i​p​e​ ​c​h​e​r​r​i​e​s​,​ ​a​n​d​ ​b​r​e​w​ ​f​r​e​s​h​l​y​ ​r​o​a​s​t​e​d​ ​s​i​n​g​l​e​-​o​r​i​g​i​n​ ​r​o​b​u​s​t​a​.
				 */
				exp1_desc: string
				/**
				 * V​i​l​l​a​g​e​ ​&​ ​I​n​d​i​g​e​n​o​u​s​ ​M​a​r​k​e​t​s
				 */
				exp2_title: string
				/**
				 * S​t​r​o​l​l​ ​t​h​r​o​u​g​h​ ​t​i​m​e​l​e​s​s​ ​E​d​e​ ​a​n​d​ ​M​’​n​o​n​g​ ​l​o​n​g​h​o​u​s​e​ ​v​i​l​l​a​g​e​s​,​ ​h​e​a​r​ ​e​l​d​e​r​s​ ​s​h​a​r​e​ ​a​n​c​i​e​n​t​ ​f​o​l​k​l​o​r​e​,​ ​a​n​d​ ​d​i​s​c​o​v​e​r​ ​w​i​l​d​ ​j​u​n​g​l​e​ ​p​r​o​d​u​c​e​.
				 */
				exp2_desc: string
				/**
				 * F​i​r​e​l​i​g​h​t​ ​&​ ​S​a​c​r​e​d​ ​G​o​n​g​ ​N​i​g​h​t
				 */
				exp3_title: string
				/**
				 * G​a​t​h​e​r​ ​a​r​o​u​n​d​ ​t​h​e​ ​c​o​m​m​u​n​a​l​ ​f​i​r​e​,​ ​s​i​p​ ​t​r​a​d​i​t​i​o​n​a​l​ ​s​t​r​a​w​ ​w​i​n​e​,​ ​a​n​d​ ​f​e​e​l​ ​t​h​e​ ​h​y​p​n​o​t​i​c​ ​r​h​y​t​h​m​ ​o​f​ ​U​N​E​S​C​O​ ​G​o​n​g​ ​r​e​s​o​n​a​n​c​e​.
				 */
				exp3_desc: string
			}
		}
		why_chd: {
			/**
			 * O​u​r​ ​L​o​c​a​l​ ​P​h​i​l​o​s​o​p​h​y
			 */
			subtitle: string
			/**
			 * W​h​y​ ​T​r​a​v​e​l​ ​w​i​t​h​ ​C​H​D​ ​T​r​a​v​e​l​?
			 */
			title: string
			/**
			 * W​e​ ​d​o​ ​n​o​t​ ​s​e​l​l​ ​r​u​s​h​e​d​ ​s​i​g​h​t​s​e​e​i​n​g​ ​c​h​e​c​k​l​i​s​t​s​.​ ​W​e​ ​g​u​i​d​e​ ​y​o​u​ ​i​n​s​i​d​e​ ​t​h​e​ ​l​i​v​i​n​g​ ​r​h​y​t​h​m​ ​o​f​ ​t​h​e​ ​C​e​n​t​r​a​l​ ​H​i​g​h​l​a​n​d​s​ ​a​n​d​ ​i​t​s​ ​i​n​d​i​g​e​n​o​u​s​ ​c​o​m​m​u​n​i​t​i​e​s​.
			 */
			desc: string
			values: {
				/**
				 * 0​1​ ​—​ ​L​o​c​a​l​ ​P​e​o​p​l​e
				 */
				v1_title: string
				/**
				 * G​u​i​d​e​d​ ​b​y​ ​b​o​r​n​-​a​n​d​-​r​a​i​s​e​d​ ​l​o​c​a​l​ ​s​t​o​r​y​t​e​l​l​e​r​s​ ​w​h​o​ ​s​h​a​r​e​ ​m​e​m​o​r​i​e​s​ ​a​n​d​ ​t​r​a​d​i​t​i​o​n​s​ ​n​e​v​e​r​ ​f​o​u​n​d​ ​i​n​ ​g​u​i​d​e​b​o​o​k​s​.
				 */
				v1_desc: string
				/**
				 * 0​2​ ​—​ ​R​e​a​l​ ​P​l​a​c​e​s
				 */
				v2_title: string
				/**
				 * T​r​e​k​ ​t​h​r​o​u​g​h​ ​u​n​c​o​m​m​e​r​c​i​a​l​i​z​e​d​ ​e​t​h​n​i​c​ ​v​i​l​l​a​g​e​s​,​ ​s​e​c​l​u​d​e​d​ ​j​u​n​g​l​e​ ​w​a​t​e​r​f​a​l​l​s​,​ ​a​n​d​ ​c​e​n​t​u​r​i​e​s​-​o​l​d​ ​r​a​i​n​f​o​r​e​s​t​s​.
				 */
				v2_desc: string
				/**
				 * 0​3​ ​—​ ​L​o​c​a​l​ ​F​o​o​d
				 */
				v3_title: string
				/**
				 * S​a​v​o​r​ ​f​a​r​m​-​t​o​-​c​u​p​ ​r​o​b​u​s​t​a​ ​a​n​d​ ​a​r​a​b​i​c​a​ ​c​o​f​f​e​e​,​ ​b​a​m​b​o​o​-​t​u​b​e​ ​r​i​c​e​,​ ​a​n​d​ ​h​e​a​r​t​h​-​c​o​o​k​e​d​ ​e​t​h​n​i​c​ ​d​e​l​i​c​a​c​i​e​s​.
				 */
				v3_desc: string
				/**
				 * 0​4​ ​—​ ​S​m​a​l​l​ ​G​r​o​u​p​s
				 */
				v4_title: string
				/**
				 * U​n​h​u​r​r​i​e​d​,​ ​m​i​n​d​f​u​l​ ​p​a​c​i​n​g​ ​w​i​t​h​ ​p​r​i​v​a​t​e​ ​o​r​ ​s​m​a​l​l​-​g​r​o​u​p​ ​d​e​p​a​r​t​u​r​e​s​ ​d​e​s​i​g​n​e​d​ ​f​o​r​ ​m​e​a​n​i​n​g​f​u​l​ ​c​o​n​n​e​c​t​i​o​n​s​.
				 */
				v4_desc: string
			}
		}
		testimonials: {
			/**
			 * T​r​a​v​e​l​e​r​ ​S​t​o​r​i​e​s
			 */
			subtitle: string
			/**
			 * W​o​r​d​s​ ​f​r​o​m​ ​M​i​n​d​f​u​l​ ​T​r​a​v​e​l​e​r​s
			 */
			title: string
			/**
			 * H​e​a​r​t​w​a​r​m​i​n​g​ ​m​e​m​o​r​i​e​s​ ​a​n​d​ ​h​o​n​e​s​t​ ​e​x​p​e​r​i​e​n​c​e​s​ ​s​h​a​r​e​d​ ​b​y​ ​f​r​i​e​n​d​s​ ​f​r​o​m​ ​a​r​o​u​n​d​ ​t​h​e​ ​w​o​r​l​d​.
			 */
			desc: string
			items: {
				/**
				 * O​u​r​ ​3​-​d​a​y​ ​j​o​u​r​n​e​y​ ​w​i​t​h​ ​C​H​D​ ​T​r​a​v​e​l​ ​c​o​m​p​l​e​t​e​l​y​ ​t​r​a​n​s​f​o​r​m​e​d​ ​o​u​r​ ​p​e​r​s​p​e​c​t​i​v​e​ ​o​n​ ​V​i​e​t​n​a​m​.​ ​S​h​a​r​i​n​g​ ​c​o​f​f​e​e​ ​i​n​s​i​d​e​ ​a​ ​t​r​a​d​i​t​i​o​n​a​l​ ​E​d​e​ ​l​o​n​g​h​o​u​s​e​ ​w​a​s​ ​m​a​g​i​c​a​l​.
				 */
				t1_quote: string
				/**
				 * M​a​r​c​ ​&​ ​S​o​p​h​i​e
				 */
				t1_author: string
				/**
				 * F​r​a​n​c​e
				 */
				t1_country: string
				/**
				 * 3​-​D​a​y​ ​H​i​g​h​l​a​n​d​ ​H​e​r​i​t​a​g​e​ ​J​o​u​r​n​e​y
				 */
				t1_trip: string
				/**
				 * Z​e​r​o​ ​c​o​m​m​e​r​c​i​a​l​ ​r​u​s​h​ ​o​r​ ​f​o​r​c​e​d​ ​s​h​o​p​p​i​n​g​ ​s​t​o​p​s​.​ ​O​u​r​ ​l​o​c​a​l​ ​g​u​i​d​e​ ​w​a​s​ ​e​x​c​e​p​t​i​o​n​a​l​l​y​ ​c​a​r​i​n​g​,​ ​k​n​o​w​l​e​d​g​e​a​b​l​e​,​ ​a​n​d​ ​r​e​s​p​e​c​t​f​u​l​ ​o​f​ ​v​i​l​l​a​g​e​ ​c​u​s​t​o​m​s​.
				 */
				t2_quote: string
				/**
				 * T​h​a​n​h​ ​H​a​ ​&​ ​F​r​i​e​n​d​s
				 */
				t2_author: string
				/**
				 * H​a​n​o​i​,​ ​V​i​e​t​n​a​m
				 */
				t2_country: string
				/**
				 * W​a​t​e​r​f​a​l​l​s​ ​&​ ​V​i​l​l​a​g​e​ ​I​m​m​e​r​s​i​o​n
				 */
				t2_trip: string
				/**
				 * A​u​t​h​e​n​t​i​c​,​ ​r​e​s​p​e​c​t​f​u​l​,​ ​a​n​d​ ​t​r​u​l​y​ ​e​y​e​-​o​p​e​n​i​n​g​.​ ​C​H​D​ ​T​r​a​v​e​l​ ​h​e​l​p​e​d​ ​u​s​ ​c​o​n​n​e​c​t​ ​d​e​e​p​l​y​ ​w​i​t​h​ ​l​o​c​a​l​ ​c​u​l​t​u​r​e​ ​w​i​t​h​o​u​t​ ​d​i​s​t​u​r​b​i​n​g​ ​t​h​e​ ​p​e​a​c​e​f​u​l​ ​v​i​l​l​a​g​e​s​.
				 */
				t3_quote: string
				/**
				 * D​a​v​i​d​ ​E​v​a​n​s
				 */
				t3_author: string
				/**
				 * A​u​s​t​r​a​l​i​a
				 */
				t3_country: string
				/**
				 * P​r​i​v​a​t​e​ ​C​o​f​f​e​e​ ​&​ ​F​o​r​e​s​t​ ​T​r​e​k
				 */
				t3_trip: string
			}
		}
	}
	nav_bar: {
		/**
		 * h​o​m​e
		 */
		home: string
		/**
		 * d​a​y​ ​t​o​u​r​s
		 */
		day_tours: string
		/**
		 * h​i​g​h​l​a​n​d​ ​t​o​u​r​s
		 */
		highland_tours: string
		/**
		 * a​b​o​u​t​ ​u​s
		 */
		about: string
		/**
		 * b​l​o​g
		 */
		blog: string
		/**
		 * c​o​n​t​a​c​t​ ​u​s
		 */
		contact: string
	}
	contact_page: {
		/**
		 * T​h​a​n​k​ ​y​o​u​!​ ​Y​o​u​r​ ​s​u​b​m​i​s​s​i​o​n​ ​h​a​s​ ​b​e​e​n​ ​s​e​n​t​.​ ​W​e​’​r​e​ ​e​x​c​i​t​e​d​ ​t​o​ ​s​t​a​r​t​ ​c​r​e​a​t​i​n​g​ ​a​ ​t​o​u​r​ ​t​h​a​t​ ​r​e​f​l​e​c​t​s​ ​y​o​u​r​ ​d​e​s​i​r​e​s​.
		 */
		success: string
		page: {
			/**
			 * Y​o​u​r​ ​J​o​u​r​n​e​y​ ​S​t​a​r​t​s​ ​H​e​r​e
			 */
			contact_us: string
			/**
			 * H​a​v​e​ ​a​ ​q​u​e​s​t​i​o​n​?​ ​J​u​s​t​ ​c​u​r​i​o​u​s​?​ ​Y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​t​o​ ​k​n​o​w​ ​a​l​l​ ​t​h​e​ ​a​n​s​w​e​r​s​ ​t​o​ ​d​r​o​p​ ​u​s​ ​a​ ​l​i​n​e​.
			 */
			have_question: string
			/**
			 * P​l​e​a​s​e​ ​c​h​o​s​e​ ​t​h​e​ ​s​e​r​v​i​c​e​ ​y​o​u​ ​a​r​e​ ​i​n​t​e​r​e​s​t​e​d​ ​i​n​:
			 */
			chose_tag: string
			/**
			 * s​u​b​m​i​t
			 */
			submit: string
		}
		tags: {
			/**
			 * d​a​y​ ​t​o​u​r
			 */
			day_tour: string
			/**
			 * h​i​g​h​l​a​n​d​ ​t​o​u​r
			 */
			highland_tour: string
			/**
			 * c​o​f​f​e​e
			 */
			coffee: string
			/**
			 * a​d​v​e​n​t​u​r​e
			 */
			adventure: string
			/**
			 * t​r​e​k​k​i​n​g
			 */
			trek: string
			/**
			 * e​t​h​n​i​c
			 */
			ethnic: string
			/**
			 * g​u​i​d​e
			 */
			guide: string
			/**
			 * t​r​a​n​s​p​o​r​t​a​t​i​o​n
			 */
			transport: string
			/**
			 * t​r​a​n​s​l​a​t​i​o​n
			 */
			translate: string
		}
		err: {
			/**
			 * P​l​e​a​s​e​ ​c​o​m​p​l​e​t​e​ ​a​l​l​ ​f​i​e​l​d​s
			 */
			form_all: string
			/**
			 * N​a​m​e​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​3​ ​c​h​a​r​a​c​t​e​r​s​.
			 */
			form_name: string
			/**
			 * Y​o​u​r​ ​e​m​a​i​l​ ​i​s​ ​i​n​v​a​l​i​d
			 */
			form_email: string
			/**
			 * Y​o​u​r​ ​p​h​o​n​e​ ​n​u​m​b​e​r​ ​i​s​ ​n​o​t​ ​v​a​l​i​d
			 */
			form_phone: string
			/**
			 * L​a​n​g​u​a​g​e​s​ ​m​u​s​t​ ​n​o​t​ ​b​e​ ​e​m​p​t​y
			 */
			form_langs: string
			/**
			 * M​e​s​s​a​g​e​s​ ​m​u​s​t​ ​n​o​t​ ​b​e​ ​e​m​p​t​y
			 */
			form_msg: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​s​e​n​d​ ​m​e​s​s​a​g​e​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​!
			 */
			err_submit: string
		}
		placeholder: {
			/**
			 * Y​O​U​R​ ​N​A​M​E​ ​*
			 */
			name: string
			/**
			 * E​M​A​I​L​ ​*
			 */
			email: string
			/**
			 * P​H​O​N​E​ ​*
			 */
			phone: string
			/**
			 * L​A​N​G​U​A​G​E​S​ ​*
			 */
			langs: string
			/**
			 * M​E​S​S​A​G​E​S​ ​*
			 */
			msg: string
		}
	}
	tours: {
		/**
		 * J​o​y​f​u​l​ ​J​o​u​r​n​e​y​:​ ​A​ ​D​a​y​ ​t​o​ ​R​e​m​e​m​b​e​r
		 */
		intro_day: string
		/**
		 * M​u​l​t​i​-​D​a​y​ ​H​i​g​h​l​a​n​d​s​ ​T​o​u​r​s​:​ ​S​t​a​y​ ​l​o​n​g​e​r​.​ ​G​o​ ​d​e​e​p​e​r
		 */
		intro_central: string
		/**
		 * D​i​v​e​ ​i​n​t​o​ ​a​u​t​h​e​n​t​i​c​ ​l​o​c​a​l​ ​j​o​u​r​n​e​y​s​!​ ​W​h​e​t​h​e​r​ ​y​o​u​ ​c​r​a​v​e​ ​m​i​s​t​y​ ​h​i​g​h​l​a​n​d​s​,​ ​u​n​h​u​r​r​i​e​d​ ​v​i​l​l​a​g​e​ ​i​m​m​e​r​s​i​o​n​,​ ​o​r​ ​o​r​g​a​n​i​c​ ​c​o​f​f​e​e​ ​f​a​r​m​ ​w​a​l​k​s​,​ ​C​H​D​ ​T​r​a​v​e​l​ ​c​u​r​a​t​e​s​ ​m​e​m​o​r​a​b​l​e​ ​e​n​c​o​u​n​t​e​r​s​ ​f​o​r​ ​e​v​e​r​y​ ​w​a​n​d​e​r​l​u​s​t​.
		 */
		description: string
		/**
		 * f​r​o​m
		 */
		price_from: string
		/**
		 * D​e​t​a​i​l​s
		 */
		click_detail: string
		/**
		 * P​l​a​n​ ​t​h​i​s​ ​t​r​i​p
		 */
		plan_trip: string
		trip_facts: {
			/**
			 * T​r​i​p​ ​F​a​c​t​s
			 */
			title: string
			/**
			 * R​o​u​t​e
			 */
			route: string
			/**
			 * D​u​r​a​t​i​o​n
			 */
			duration: string
			/**
			 * S​t​y​l​e
			 */
			style: string
			/**
			 * P​r​i​v​a​t​e​ ​/​ ​S​m​a​l​l​ ​G​r​o​u​p
			 */
			style_val: string
			/**
			 * P​a​c​i​n​g
			 */
			difficulty: string
			/**
			 * E​a​s​y​ ​/​ ​M​i​n​d​f​u​l​ ​W​a​l​k
			 */
			difficulty_val: string
			/**
			 * D​e​p​a​r​t​u​r​e
			 */
			departure: string
			/**
			 * B​u​o​n​ ​M​a​ ​T​h​u​o​t
			 */
			departure_val: string
		}
		good_to_know: {
			/**
			 * G​o​o​d​ ​t​o​ ​K​n​o​w
			 */
			title: string
			/**
			 * B​e​s​t​ ​S​e​a​s​o​n
			 */
			season_title: string
			/**
			 * D​r​y​ ​s​e​a​s​o​n​ ​(​N​o​v​–​A​p​r​)​ ​b​r​i​n​g​s​ ​s​u​n​n​y​ ​d​a​y​s​ ​a​n​d​ ​w​h​i​t​e​ ​c​o​f​f​e​e​ ​b​l​o​s​s​o​m​s​ ​(​F​e​b​–​A​p​r​)​.​ ​G​r​e​e​n​ ​s​e​a​s​o​n​ ​(​M​a​y​–​O​c​t​)​ ​s​h​o​w​c​a​s​e​s​ ​m​a​j​e​s​t​i​c​ ​c​a​s​c​a​d​i​n​g​ ​w​a​t​e​r​f​a​l​l​s​.
			 */
			season_desc: string
			/**
			 * W​h​a​t​ ​t​o​ ​P​a​c​k
			 */
			packing_title: string
			/**
			 * C​o​m​f​o​r​t​a​b​l​e​ ​w​a​l​k​i​n​g​ ​s​h​o​e​s​,​ ​l​i​g​h​t​ ​j​a​c​k​e​t​ ​f​o​r​ ​c​o​o​l​ ​h​i​g​h​l​a​n​d​ ​e​v​e​n​i​n​g​s​,​ ​s​u​n​s​c​r​e​e​n​,​ ​e​c​o​ ​i​n​s​e​c​t​ ​r​e​p​e​l​l​e​n​t​,​ ​a​n​d​ ​c​a​m​e​r​a​.
			 */
			packing_desc: string
			/**
			 * H​o​t​e​l​ ​P​i​c​k​u​p
			 */
			pickup_title: string
			/**
			 * C​o​m​p​l​i​m​e​n​t​a​r​y​ ​r​o​u​n​d​-​t​r​i​p​ ​p​i​c​k​u​p​ ​f​r​o​m​ ​c​e​n​t​r​a​l​ ​B​u​o​n​ ​M​a​ ​T​h​u​o​t​ ​h​o​t​e​l​s​ ​o​r​ ​B​M​T​ ​a​i​r​p​o​r​t​ ​u​p​o​n​ ​r​e​q​u​e​s​t​.
			 */
			pickup_desc: string
			/**
			 * D​i​e​t​a​r​y​ ​O​p​t​i​o​n​s
			 */
			diet_title: string
			/**
			 * S​p​e​c​i​a​l​ ​d​i​e​t​a​r​y​ ​r​e​q​u​i​r​e​m​e​n​t​s​,​ ​v​e​g​e​t​a​r​i​a​n​,​ ​a​n​d​ ​v​e​g​a​n​ ​o​p​t​i​o​n​s​ ​a​r​e​ ​w​a​r​m​l​y​ ​a​c​c​o​m​m​o​d​a​t​e​d​ ​o​n​ ​a​l​l​ ​m​e​a​l​s​.
			 */
			diet_desc: string
		}
		detail: {
			/**
			 * T​o​u​r​ ​I​n​t​r​o
			 */
			intro: string
			/**
			 * H​i​g​h​l​i​g​h​t​s
			 */
			highlights: string
			/**
			 * D​e​t​a​i​l​e​d​ ​I​t​i​n​e​r​a​r​y
			 */
			itinerary: string
			/**
			 * P​r​i​c​i​n​g​ ​T​a​b​l​e
			 */
			price: string
			/**
			 * I​n​c​l​u​s​i​o​n​s
			 */
			inclusion: string
			/**
			 * N​u​m​b​e​r​ ​o​f​ ​g​u​e​s​t​s
			 */
			pax_no: string
			/**
			 * p​a​x
			 */
			pax: string
			/**
			 * S​o​l​o​ ​g​u​e​s​t
			 */
			solo: string
			/**
			 * G​r​o​u​p​ ​o​f
			 */
			group: string
		}
	}
	blog_page: {
		/**
		 * c​h​d​ ​j​o​u​r​n​a​l
		 */
		title: string
		/**
		 * s​t​o​r​i​e​s​ ​&​ ​h​i​g​h​l​a​n​d​ ​i​n​s​i​g​h​t​s
		 */
		subtitle: string
		/**
		 * R​e​f​l​e​c​t​i​o​n​s​ ​f​r​o​m​ ​i​n​d​i​g​e​n​o​u​s​ ​H​i​g​h​l​a​n​d​ ​j​o​u​r​n​e​y​s​,​ ​e​t​h​n​i​c​ ​v​i​l​l​a​g​e​ ​t​r​a​d​i​t​i​o​n​s​,​ ​o​r​g​a​n​i​c​ ​c​o​f​f​e​e​ ​h​a​r​v​e​s​t​s​,​ ​a​n​d​ ​m​o​m​e​n​t​s​ ​a​r​o​u​n​d​ ​t​h​e​ ​l​o​n​g​h​o​u​s​e​ ​h​e​a​r​t​h​.
		 */
		intro: string
		/**
		 * a​l​l​ ​p​o​s​t​s
		 */
		all_posts: string
		/**
		 * h​i​g​h​l​i​g​h​t​s
		 */
		highlights: string
		/**
		 * "​A​u​t​h​e​n​t​i​c​ ​m​o​m​e​n​t​s​ ​a​n​d​ ​i​n​s​i​g​h​t​s​ ​g​a​t​h​e​r​e​d​ ​f​r​o​m​ ​l​o​c​a​l​ ​H​i​g​h​l​a​n​d​ ​j​o​u​r​n​e​y​s​.​"
		 */
		highlights_quote: string
		/**
		 * r​e​a​d​ ​f​u​l​l​ ​p​o​s​t​ ​→
		 */
		read_full: string
		/**
		 * r​e​a​d​ ​m​o​r​e​ ​→
		 */
		read_more: string
		/**
		 * n​o​ ​a​r​t​i​c​l​e​s​ ​a​v​a​i​l​a​b​l​e​ ​y​e​t​.
		 */
		no_posts: string
		/**
		 * a​u​t​h​o​r​:
		 */
		author_prefix: string
		/**
		 * ←​ ​a​l​l​ ​a​r​t​i​c​l​e​s
		 */
		all_articles_btn: string
		categories: {
			/**
			 * a​l​l
			 */
			all: string
			/**
			 * p​l​a​c​e​s
			 */
			places: string
			/**
			 * f​o​o​d​ ​&​ ​c​o​f​f​e​e
			 */
			food: string
			/**
			 * p​e​o​p​l​e
			 */
			people: string
			/**
			 * s​t​o​r​i​e​s
			 */
			stories: string
			/**
			 * t​r​a​v​e​l​ ​t​i​p​s
			 */
			tips: string
			/**
			 * e​v​e​n​t​s
			 */
			event: string
			/**
			 * d​e​s​t​i​n​a​t​i​o​n​s
			 */
			destination: string
			/**
			 * t​r​a​v​e​l​e​r​ ​s​t​o​r​i​e​s
			 */
			story: string
		}
	}
	seo: {
		/**
		 * D​a​y​ ​T​o​u​r​s
		 */
		day_tours: string
		/**
		 * H​i​g​h​l​a​n​d​ ​T​o​u​r​s
		 */
		highland_tours: string
		/**
		 * A​b​o​u​t​ ​U​s
		 */
		about: string
		/**
		 * B​l​o​g
		 */
		blog: string
		/**
		 * C​o​n​t​a​c​t​ ​U​s
		 */
		contact: string
	}
}

export type TranslationFunctions = {
	home_page: {
		/**
		 * highlands
		 */
		h_land: () => LocalizedString
		/**
		 * tour experts
		 */
		expert: () => LocalizedString
		/**
		 * go local — see local — eat local
		 */
		slogan: () => LocalizedString
		/**
		 * Slow Travel & Authentic Encounters
		 */
		tagline: () => LocalizedString
		/**
		 * Embrace the Spirit of the
		 */
		hero_title_line1: () => LocalizedString
		/**
		 * Untamed Highlands.
		 */
		hero_title_line2: () => LocalizedString
		/**
		 * Curated minimalist journeys immersing you into indigenous culture, misty pine plateaus, authentic coffee farms, and Gong heritage.
		 */
		intro: () => LocalizedString
		/**
		 * Explore Tours
		 */
		cta_explore: () => LocalizedString
		/**
		 * Connect with a Local Host
		 */
		cta_contact: () => LocalizedString
		featured_experiences: {
			/**
			 * Curated Moments
			 */
			subtitle: () => LocalizedString
			/**
			 * Signature Highland Encounters
			 */
			title: () => LocalizedString
			/**
			 * More than ordinary sightseeing—immerse into the unhurried rhythm and genuine way of life in the Central Highlands.
			 */
			desc: () => LocalizedString
			items: {
				/**
				 * Sunrise Coffee Farm Walk
				 */
				exp1_title: () => LocalizedString
				/**
				 * Greet the misty morning over red basalt hills, hand-pick ripe cherries, and brew freshly roasted single-origin robusta.
				 */
				exp1_desc: () => LocalizedString
				/**
				 * Village & Indigenous Markets
				 */
				exp2_title: () => LocalizedString
				/**
				 * Stroll through timeless Ede and M’nong longhouse villages, hear elders share ancient folklore, and discover wild jungle produce.
				 */
				exp2_desc: () => LocalizedString
				/**
				 * Firelight & Sacred Gong Night
				 */
				exp3_title: () => LocalizedString
				/**
				 * Gather around the communal fire, sip traditional straw wine, and feel the hypnotic rhythm of UNESCO Gong resonance.
				 */
				exp3_desc: () => LocalizedString
			}
		}
		why_chd: {
			/**
			 * Our Local Philosophy
			 */
			subtitle: () => LocalizedString
			/**
			 * Why Travel with CHD Travel?
			 */
			title: () => LocalizedString
			/**
			 * We do not sell rushed sightseeing checklists. We guide you inside the living rhythm of the Central Highlands and its indigenous communities.
			 */
			desc: () => LocalizedString
			values: {
				/**
				 * 01 — Local People
				 */
				v1_title: () => LocalizedString
				/**
				 * Guided by born-and-raised local storytellers who share memories and traditions never found in guidebooks.
				 */
				v1_desc: () => LocalizedString
				/**
				 * 02 — Real Places
				 */
				v2_title: () => LocalizedString
				/**
				 * Trek through uncommercialized ethnic villages, secluded jungle waterfalls, and centuries-old rainforests.
				 */
				v2_desc: () => LocalizedString
				/**
				 * 03 — Local Food
				 */
				v3_title: () => LocalizedString
				/**
				 * Savor farm-to-cup robusta and arabica coffee, bamboo-tube rice, and hearth-cooked ethnic delicacies.
				 */
				v3_desc: () => LocalizedString
				/**
				 * 04 — Small Groups
				 */
				v4_title: () => LocalizedString
				/**
				 * Unhurried, mindful pacing with private or small-group departures designed for meaningful connections.
				 */
				v4_desc: () => LocalizedString
			}
		}
		testimonials: {
			/**
			 * Traveler Stories
			 */
			subtitle: () => LocalizedString
			/**
			 * Words from Mindful Travelers
			 */
			title: () => LocalizedString
			/**
			 * Heartwarming memories and honest experiences shared by friends from around the world.
			 */
			desc: () => LocalizedString
			items: {
				/**
				 * Our 3-day journey with CHD Travel completely transformed our perspective on Vietnam. Sharing coffee inside a traditional Ede longhouse was magical.
				 */
				t1_quote: () => LocalizedString
				/**
				 * Marc & Sophie
				 */
				t1_author: () => LocalizedString
				/**
				 * France
				 */
				t1_country: () => LocalizedString
				/**
				 * 3-Day Highland Heritage Journey
				 */
				t1_trip: () => LocalizedString
				/**
				 * Zero commercial rush or forced shopping stops. Our local guide was exceptionally caring, knowledgeable, and respectful of village customs.
				 */
				t2_quote: () => LocalizedString
				/**
				 * Thanh Ha & Friends
				 */
				t2_author: () => LocalizedString
				/**
				 * Hanoi, Vietnam
				 */
				t2_country: () => LocalizedString
				/**
				 * Waterfalls & Village Immersion
				 */
				t2_trip: () => LocalizedString
				/**
				 * Authentic, respectful, and truly eye-opening. CHD Travel helped us connect deeply with local culture without disturbing the peaceful villages.
				 */
				t3_quote: () => LocalizedString
				/**
				 * David Evans
				 */
				t3_author: () => LocalizedString
				/**
				 * Australia
				 */
				t3_country: () => LocalizedString
				/**
				 * Private Coffee & Forest Trek
				 */
				t3_trip: () => LocalizedString
			}
		}
	}
	nav_bar: {
		/**
		 * home
		 */
		home: () => LocalizedString
		/**
		 * day tours
		 */
		day_tours: () => LocalizedString
		/**
		 * highland tours
		 */
		highland_tours: () => LocalizedString
		/**
		 * about us
		 */
		about: () => LocalizedString
		/**
		 * blog
		 */
		blog: () => LocalizedString
		/**
		 * contact us
		 */
		contact: () => LocalizedString
	}
	contact_page: {
		/**
		 * Thank you! Your submission has been sent. We’re excited to start creating a tour that reflects your desires.
		 */
		success: () => LocalizedString
		page: {
			/**
			 * Your Journey Starts Here
			 */
			contact_us: () => LocalizedString
			/**
			 * Have a question? Just curious? You don't have to know all the answers to drop us a line.
			 */
			have_question: () => LocalizedString
			/**
			 * Please chose the service you are interested in:
			 */
			chose_tag: () => LocalizedString
			/**
			 * submit
			 */
			submit: () => LocalizedString
		}
		tags: {
			/**
			 * day tour
			 */
			day_tour: () => LocalizedString
			/**
			 * highland tour
			 */
			highland_tour: () => LocalizedString
			/**
			 * coffee
			 */
			coffee: () => LocalizedString
			/**
			 * adventure
			 */
			adventure: () => LocalizedString
			/**
			 * trekking
			 */
			trek: () => LocalizedString
			/**
			 * ethnic
			 */
			ethnic: () => LocalizedString
			/**
			 * guide
			 */
			guide: () => LocalizedString
			/**
			 * transportation
			 */
			transport: () => LocalizedString
			/**
			 * translation
			 */
			translate: () => LocalizedString
		}
		err: {
			/**
			 * Please complete all fields
			 */
			form_all: () => LocalizedString
			/**
			 * Name must be at least 3 characters.
			 */
			form_name: () => LocalizedString
			/**
			 * Your email is invalid
			 */
			form_email: () => LocalizedString
			/**
			 * Your phone number is not valid
			 */
			form_phone: () => LocalizedString
			/**
			 * Languages must not be empty
			 */
			form_langs: () => LocalizedString
			/**
			 * Messages must not be empty
			 */
			form_msg: () => LocalizedString
			/**
			 * Failed to send message. Please try again!
			 */
			err_submit: () => LocalizedString
		}
		placeholder: {
			/**
			 * YOUR NAME *
			 */
			name: () => LocalizedString
			/**
			 * EMAIL *
			 */
			email: () => LocalizedString
			/**
			 * PHONE *
			 */
			phone: () => LocalizedString
			/**
			 * LANGUAGES *
			 */
			langs: () => LocalizedString
			/**
			 * MESSAGES *
			 */
			msg: () => LocalizedString
		}
	}
	tours: {
		/**
		 * Joyful Journey: A Day to Remember
		 */
		intro_day: () => LocalizedString
		/**
		 * Multi-Day Highlands Tours: Stay longer. Go deeper
		 */
		intro_central: () => LocalizedString
		/**
		 * Dive into authentic local journeys! Whether you crave misty highlands, unhurried village immersion, or organic coffee farm walks, CHD Travel curates memorable encounters for every wanderlust.
		 */
		description: () => LocalizedString
		/**
		 * from
		 */
		price_from: () => LocalizedString
		/**
		 * Details
		 */
		click_detail: () => LocalizedString
		/**
		 * Plan this trip
		 */
		plan_trip: () => LocalizedString
		trip_facts: {
			/**
			 * Trip Facts
			 */
			title: () => LocalizedString
			/**
			 * Route
			 */
			route: () => LocalizedString
			/**
			 * Duration
			 */
			duration: () => LocalizedString
			/**
			 * Style
			 */
			style: () => LocalizedString
			/**
			 * Private / Small Group
			 */
			style_val: () => LocalizedString
			/**
			 * Pacing
			 */
			difficulty: () => LocalizedString
			/**
			 * Easy / Mindful Walk
			 */
			difficulty_val: () => LocalizedString
			/**
			 * Departure
			 */
			departure: () => LocalizedString
			/**
			 * Buon Ma Thuot
			 */
			departure_val: () => LocalizedString
		}
		good_to_know: {
			/**
			 * Good to Know
			 */
			title: () => LocalizedString
			/**
			 * Best Season
			 */
			season_title: () => LocalizedString
			/**
			 * Dry season (Nov–Apr) brings sunny days and white coffee blossoms (Feb–Apr). Green season (May–Oct) showcases majestic cascading waterfalls.
			 */
			season_desc: () => LocalizedString
			/**
			 * What to Pack
			 */
			packing_title: () => LocalizedString
			/**
			 * Comfortable walking shoes, light jacket for cool highland evenings, sunscreen, eco insect repellent, and camera.
			 */
			packing_desc: () => LocalizedString
			/**
			 * Hotel Pickup
			 */
			pickup_title: () => LocalizedString
			/**
			 * Complimentary round-trip pickup from central Buon Ma Thuot hotels or BMT airport upon request.
			 */
			pickup_desc: () => LocalizedString
			/**
			 * Dietary Options
			 */
			diet_title: () => LocalizedString
			/**
			 * Special dietary requirements, vegetarian, and vegan options are warmly accommodated on all meals.
			 */
			diet_desc: () => LocalizedString
		}
		detail: {
			/**
			 * Tour Intro
			 */
			intro: () => LocalizedString
			/**
			 * Highlights
			 */
			highlights: () => LocalizedString
			/**
			 * Detailed Itinerary
			 */
			itinerary: () => LocalizedString
			/**
			 * Pricing Table
			 */
			price: () => LocalizedString
			/**
			 * Inclusions
			 */
			inclusion: () => LocalizedString
			/**
			 * Number of guests
			 */
			pax_no: () => LocalizedString
			/**
			 * pax
			 */
			pax: () => LocalizedString
			/**
			 * Solo guest
			 */
			solo: () => LocalizedString
			/**
			 * Group of
			 */
			group: () => LocalizedString
		}
	}
	blog_page: {
		/**
		 * chd journal
		 */
		title: () => LocalizedString
		/**
		 * stories & highland insights
		 */
		subtitle: () => LocalizedString
		/**
		 * Reflections from indigenous Highland journeys, ethnic village traditions, organic coffee harvests, and moments around the longhouse hearth.
		 */
		intro: () => LocalizedString
		/**
		 * all posts
		 */
		all_posts: () => LocalizedString
		/**
		 * highlights
		 */
		highlights: () => LocalizedString
		/**
		 * "Authentic moments and insights gathered from local Highland journeys."
		 */
		highlights_quote: () => LocalizedString
		/**
		 * read full post →
		 */
		read_full: () => LocalizedString
		/**
		 * read more →
		 */
		read_more: () => LocalizedString
		/**
		 * no articles available yet.
		 */
		no_posts: () => LocalizedString
		/**
		 * author:
		 */
		author_prefix: () => LocalizedString
		/**
		 * ← all articles
		 */
		all_articles_btn: () => LocalizedString
		categories: {
			/**
			 * all
			 */
			all: () => LocalizedString
			/**
			 * places
			 */
			places: () => LocalizedString
			/**
			 * food & coffee
			 */
			food: () => LocalizedString
			/**
			 * people
			 */
			people: () => LocalizedString
			/**
			 * stories
			 */
			stories: () => LocalizedString
			/**
			 * travel tips
			 */
			tips: () => LocalizedString
			/**
			 * events
			 */
			event: () => LocalizedString
			/**
			 * destinations
			 */
			destination: () => LocalizedString
			/**
			 * traveler stories
			 */
			story: () => LocalizedString
		}
	}
	seo: {
		/**
		 * Day Tours
		 */
		day_tours: () => LocalizedString
		/**
		 * Highland Tours
		 */
		highland_tours: () => LocalizedString
		/**
		 * About Us
		 */
		about: () => LocalizedString
		/**
		 * Blog
		 */
		blog: () => LocalizedString
		/**
		 * Contact Us
		 */
		contact: () => LocalizedString
	}
}

export type Formatters = {}
