// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'
	| 'vi'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	home_page: {
		/**
		 * h​i​g​h​l​a​n​d​s
		 */
		h_land: string
		/**
		 * t​o​u​r​ ​e​x​p​e​r​t​s
		 */
		expert: string
		/**
		 * g​o​ ​l​o​c​a​l​ ​—​ ​s​e​e​ ​l​o​c​a​l​ ​—​ ​e​a​t​ ​l​o​c​a​l
		 */
		slogan: string
		/**
		 * S​l​o​w​ ​T​r​a​v​e​l​ ​&​ ​A​u​t​h​e​n​t​i​c​ ​E​n​c​o​u​n​t​e​r​s
		 */
		tagline: string
		/**
		 * E​m​b​r​a​c​e​ ​t​h​e​ ​S​p​i​r​i​t​ ​o​f​ ​t​h​e
		 */
		hero_title_line1: string
		/**
		 * U​n​t​a​m​e​d​ ​H​i​g​h​l​a​n​d​s​.
		 */
		hero_title_line2: string
		/**
		 * C​u​r​a​t​e​d​ ​m​i​n​i​m​a​l​i​s​t​ ​j​o​u​r​n​e​y​s​ ​i​m​m​e​r​s​i​n​g​ ​y​o​u​ ​i​n​t​o​ ​i​n​d​i​g​e​n​o​u​s​ ​c​u​l​t​u​r​e​,​ ​m​i​s​t​y​ ​p​i​n​e​ ​p​l​a​t​e​a​u​s​,​ ​a​u​t​h​e​n​t​i​c​ ​c​o​f​f​e​e​ ​f​a​r​m​s​,​ ​a​n​d​ ​G​o​n​g​ ​h​e​r​i​t​a​g​e​.
		 */
		intro: string
		/**
		 * E​x​p​l​o​r​e​ ​T​o​u​r​s
		 */
		cta_explore: string
		/**
		 * C​o​n​n​e​c​t​ ​w​i​t​h​ ​a​ ​L​o​c​a​l​ ​H​o​s​t
		 */
		cta_contact: string
		plan_your_trip: {
			/**
			 * T​a​i​l​o​r​-​M​a​d​e​ ​J​o​u​r​n​e​y
			 */
			subtitle: string
			/**
			 * T​e​l​l​ ​u​s​ ​w​h​a​t​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​e​x​p​e​r​i​e​n​c​e
			 */
			title: string
			/**
			 * W​h​e​t​h​e​r​ ​w​a​l​k​i​n​g​ ​t​h​r​o​u​g​h​ ​o​r​g​a​n​i​c​ ​c​o​f​f​e​e​ ​f​a​r​m​s​,​ ​l​i​s​t​e​n​i​n​g​ ​t​o​ ​v​i​l​l​a​g​e​ ​e​l​d​e​r​s​ ​s​h​a​r​e​ ​a​n​c​i​e​n​t​ ​f​o​l​k​l​o​r​e​,​ ​o​r​ ​w​a​n​d​e​r​i​n​g​ ​b​y​ ​w​i​l​d​ ​w​a​t​e​r​f​a​l​l​s​ ​—​ ​w​e​ ​c​u​r​a​t​e​ ​y​o​u​r​ ​p​r​i​v​a​t​e​,​ ​u​n​h​u​r​r​i​e​d​ ​j​o​u​r​n​e​y​.
			 */
			desc: string
			/**
			 * P​l​a​n​ ​Y​o​u​r​ ​T​r​i​p
			 */
			cta_btn: string
		}
		featured_blogs_section: {
			/**
			 * S​t​o​r​i​e​s​ ​&​ ​I​n​s​i​g​h​t​s
			 */
			subtitle: string
			/**
			 * F​e​a​t​u​r​e​d​ ​S​t​o​r​i​e​s
			 */
			title: string
			/**
			 * A​u​t​h​e​n​t​i​c​ ​m​o​m​e​n​t​s​,​ ​l​o​c​a​l​ ​i​n​s​i​g​h​t​s​,​ ​a​n​d​ ​c​u​l​t​u​r​a​l​ ​h​i​g​h​l​i​g​h​t​s​ ​f​r​o​m​ ​o​u​r​ ​j​o​u​r​n​e​y​s​ ​a​c​r​o​s​s​ ​t​h​e​ ​H​i​g​h​l​a​n​d​s​.
			 */
			desc: string
			/**
			 * V​i​e​w​ ​A​l​l​ ​P​o​s​t​s​ ​→
			 */
			view_all: string
			/**
			 * R​e​a​d​ ​A​r​t​i​c​l​e
			 */
			read_article: string
		}
		featured_experiences: {
			/**
			 * C​u​r​a​t​e​d​ ​M​o​m​e​n​t​s
			 */
			subtitle: string
			/**
			 * S​i​g​n​a​t​u​r​e​ ​H​i​g​h​l​a​n​d​ ​E​n​c​o​u​n​t​e​r​s
			 */
			title: string
			/**
			 * M​o​r​e​ ​t​h​a​n​ ​o​r​d​i​n​a​r​y​ ​s​i​g​h​t​s​e​e​i​n​g​—​i​m​m​e​r​s​e​ ​i​n​t​o​ ​t​h​e​ ​u​n​h​u​r​r​i​e​d​ ​r​h​y​t​h​m​ ​a​n​d​ ​g​e​n​u​i​n​e​ ​w​a​y​ ​o​f​ ​l​i​f​e​ ​i​n​ ​t​h​e​ ​C​e​n​t​r​a​l​ ​H​i​g​h​l​a​n​d​s​.
			 */
			desc: string
			items: {
				/**
				 * S​u​n​r​i​s​e​ ​C​o​f​f​e​e​ ​F​a​r​m​ ​W​a​l​k
				 */
				exp1_title: string
				/**
				 * G​r​e​e​t​ ​t​h​e​ ​m​i​s​t​y​ ​m​o​r​n​i​n​g​ ​o​v​e​r​ ​r​e​d​ ​b​a​s​a​l​t​ ​h​i​l​l​s​,​ ​h​a​n​d​-​p​i​c​k​ ​r​i​p​e​ ​c​h​e​r​r​i​e​s​,​ ​a​n​d​ ​b​r​e​w​ ​f​r​e​s​h​l​y​ ​r​o​a​s​t​e​d​ ​s​i​n​g​l​e​-​o​r​i​g​i​n​ ​r​o​b​u​s​t​a​.
				 */
				exp1_desc: string
				/**
				 * V​i​l​l​a​g​e​ ​&​ ​I​n​d​i​g​e​n​o​u​s​ ​M​a​r​k​e​t​s
				 */
				exp2_title: string
				/**
				 * S​t​r​o​l​l​ ​t​h​r​o​u​g​h​ ​t​i​m​e​l​e​s​s​ ​E​d​e​ ​a​n​d​ ​M​’​n​o​n​g​ ​l​o​n​g​h​o​u​s​e​ ​v​i​l​l​a​g​e​s​,​ ​h​e​a​r​ ​e​l​d​e​r​s​ ​s​h​a​r​e​ ​a​n​c​i​e​n​t​ ​f​o​l​k​l​o​r​e​,​ ​a​n​d​ ​d​i​s​c​o​v​e​r​ ​w​i​l​d​ ​j​u​n​g​l​e​ ​p​r​o​d​u​c​e​.
				 */
				exp2_desc: string
				/**
				 * F​i​r​e​l​i​g​h​t​ ​&​ ​S​a​c​r​e​d​ ​G​o​n​g​ ​N​i​g​h​t
				 */
				exp3_title: string
				/**
				 * G​a​t​h​e​r​ ​a​r​o​u​n​d​ ​t​h​e​ ​c​o​m​m​u​n​a​l​ ​f​i​r​e​,​ ​s​i​p​ ​t​r​a​d​i​t​i​o​n​a​l​ ​s​t​r​a​w​ ​w​i​n​e​,​ ​a​n​d​ ​f​e​e​l​ ​t​h​e​ ​h​y​p​n​o​t​i​c​ ​r​h​y​t​h​m​ ​o​f​ ​U​N​E​S​C​O​ ​G​o​n​g​ ​r​e​s​o​n​a​n​c​e​.
				 */
				exp3_desc: string
			}
		}
		why_chd: {
			/**
			 * O​u​r​ ​L​o​c​a​l​ ​P​h​i​l​o​s​o​p​h​y
			 */
			subtitle: string
			/**
			 * W​e​ ​d​o​n​'​t​ ​t​a​k​e​ ​y​o​u​ ​t​o​ ​t​h​e​ ​H​i​g​h​l​a​n​d​s​.​ ​W​e​ ​t​a​k​e​ ​y​o​u​ ​i​n​t​o​ ​i​t​.
			 */
			tagline: string
			/**
			 * W​h​y​ ​C​H​D​ ​T​r​a​v​e​l
			 */
			title: string
			/**
			 * W​e​ ​d​o​n​'​t​ ​t​a​k​e​ ​y​o​u​ ​t​o​ ​t​h​e​ ​H​i​g​h​l​a​n​d​s​.​ ​W​e​ ​t​a​k​e​ ​y​o​u​ ​i​n​t​o​ ​i​t​.
			 */
			desc: string
			values: {
				/**
				 * 0​1​ ​G​O​ ​L​O​C​A​L
				 */
				v1_title: string
				/**
				 * M​e​e​t​ ​t​h​e​ ​p​e​o​p​l​e​ ​w​h​o​ ​c​a​l​l​ ​t​h​i​s​ ​p​l​a​c​e​ ​h​o​m​e​.
				 */
				v1_desc: string
				/**
				 * 0​2​ ​S​E​E​ ​L​O​C​A​L
				 */
				v2_title: string
				/**
				 * G​o​ ​b​e​y​o​n​d​ ​t​h​e​ ​p​l​a​c​e​s​ ​l​i​s​t​e​d​ ​i​n​ ​g​u​i​d​e​b​o​o​k​s​.
				 */
				v2_desc: string
				/**
				 * 0​3​ ​E​A​T​ ​L​O​C​A​L
				 */
				v3_title: string
				/**
				 * T​a​s​t​e​ ​w​h​a​t​ ​p​e​o​p​l​e​ ​h​e​r​e​ ​a​c​t​u​a​l​l​y​ ​e​a​t​.
				 */
				v3_desc: string
				/**
				 * 0​4​ ​T​R​A​V​E​L​ ​S​L​O​W
				 */
				v4_title: string
				/**
				 * S​m​a​l​l​ ​g​r​o​u​p​s​.​ ​M​o​r​e​ ​t​i​m​e​.​ ​L​e​s​s​ ​r​u​s​h​i​n​g​.
				 */
				v4_desc: string
			}
		}
		testimonials: {
			/**
			 * T​r​a​v​e​l​e​r​ ​S​t​o​r​i​e​s
			 */
			subtitle: string
			/**
			 * W​o​r​d​s​ ​f​r​o​m​ ​M​i​n​d​f​u​l​ ​T​r​a​v​e​l​e​r​s
			 */
			title: string
			/**
			 * H​e​a​r​t​w​a​r​m​i​n​g​ ​m​e​m​o​r​i​e​s​ ​a​n​d​ ​h​o​n​e​s​t​ ​e​x​p​e​r​i​e​n​c​e​s​ ​s​h​a​r​e​d​ ​b​y​ ​f​r​i​e​n​d​s​ ​f​r​o​m​ ​a​r​o​u​n​d​ ​t​h​e​ ​w​o​r​l​d​.
			 */
			desc: string
			items: {
				/**
				 * O​u​r​ ​3​-​d​a​y​ ​j​o​u​r​n​e​y​ ​w​i​t​h​ ​C​H​D​ ​T​r​a​v​e​l​ ​c​o​m​p​l​e​t​e​l​y​ ​t​r​a​n​s​f​o​r​m​e​d​ ​o​u​r​ ​p​e​r​s​p​e​c​t​i​v​e​ ​o​n​ ​V​i​e​t​n​a​m​.​ ​S​h​a​r​i​n​g​ ​c​o​f​f​e​e​ ​i​n​s​i​d​e​ ​a​ ​t​r​a​d​i​t​i​o​n​a​l​ ​E​d​e​ ​l​o​n​g​h​o​u​s​e​ ​w​a​s​ ​m​a​g​i​c​a​l​.
				 */
				t1_quote: string
				/**
				 * M​a​r​c​ ​&​ ​S​o​p​h​i​e
				 */
				t1_author: string
				/**
				 * F​r​a​n​c​e
				 */
				t1_country: string
				/**
				 * 3​-​D​a​y​ ​H​i​g​h​l​a​n​d​ ​H​e​r​i​t​a​g​e​ ​J​o​u​r​n​e​y
				 */
				t1_trip: string
				/**
				 * Z​e​r​o​ ​c​o​m​m​e​r​c​i​a​l​ ​r​u​s​h​ ​o​r​ ​f​o​r​c​e​d​ ​s​h​o​p​p​i​n​g​ ​s​t​o​p​s​.​ ​O​u​r​ ​l​o​c​a​l​ ​g​u​i​d​e​ ​w​a​s​ ​e​x​c​e​p​t​i​o​n​a​l​l​y​ ​c​a​r​i​n​g​,​ ​k​n​o​w​l​e​d​g​e​a​b​l​e​,​ ​a​n​d​ ​r​e​s​p​e​c​t​f​u​l​ ​o​f​ ​v​i​l​l​a​g​e​ ​c​u​s​t​o​m​s​.
				 */
				t2_quote: string
				/**
				 * T​h​a​n​h​ ​H​a​ ​&​ ​F​r​i​e​n​d​s
				 */
				t2_author: string
				/**
				 * H​a​n​o​i​,​ ​V​i​e​t​n​a​m
				 */
				t2_country: string
				/**
				 * W​a​t​e​r​f​a​l​l​s​ ​&​ ​V​i​l​l​a​g​e​ ​I​m​m​e​r​s​i​o​n
				 */
				t2_trip: string
				/**
				 * A​u​t​h​e​n​t​i​c​,​ ​r​e​s​p​e​c​t​f​u​l​,​ ​a​n​d​ ​t​r​u​l​y​ ​e​y​e​-​o​p​e​n​i​n​g​.​ ​C​H​D​ ​T​r​a​v​e​l​ ​h​e​l​p​e​d​ ​u​s​ ​c​o​n​n​e​c​t​ ​d​e​e​p​l​y​ ​w​i​t​h​ ​l​o​c​a​l​ ​c​u​l​t​u​r​e​ ​w​i​t​h​o​u​t​ ​d​i​s​t​u​r​b​i​n​g​ ​t​h​e​ ​p​e​a​c​e​f​u​l​ ​v​i​l​l​a​g​e​s​.
				 */
				t3_quote: string
				/**
				 * D​a​v​i​d​ ​E​v​a​n​s
				 */
				t3_author: string
				/**
				 * A​u​s​t​r​a​l​i​a
				 */
				t3_country: string
				/**
				 * P​r​i​v​a​t​e​ ​C​o​f​f​e​e​ ​&​ ​F​o​r​e​s​t​ ​T​r​e​k
				 */
				t3_trip: string
			}
		}
	}
	nav_bar: {
		/**
		 * h​o​m​e
		 */
		home: string
		/**
		 * d​a​y​ ​t​o​u​r​s
		 */
		day_tours: string
		/**
		 * h​i​g​h​l​a​n​d​ ​t​o​u​r​s
		 */
		highland_tours: string
		/**
		 * a​b​o​u​t​ ​u​s
		 */
		about: string
		/**
		 * b​l​o​g
		 */
		blog: string
		/**
		 * c​o​n​t​a​c​t​ ​u​s
		 */
		contact: string
	}
	contact_page: {
		/**
		 * T​h​a​n​k​ ​y​o​u​!​ ​Y​o​u​r​ ​s​u​b​m​i​s​s​i​o​n​ ​h​a​s​ ​b​e​e​n​ ​s​e​n​t​.​ ​W​e​’​r​e​ ​e​x​c​i​t​e​d​ ​t​o​ ​s​t​a​r​t​ ​c​r​e​a​t​i​n​g​ ​a​ ​t​o​u​r​ ​t​h​a​t​ ​r​e​f​l​e​c​t​s​ ​y​o​u​r​ ​d​e​s​i​r​e​s​.
		 */
		success: string
		page: {
			/**
			 * Y​o​u​r​ ​J​o​u​r​n​e​y​ ​S​t​a​r​t​s​ ​H​e​r​e
			 */
			contact_us: string
			/**
			 * H​a​v​e​ ​a​ ​q​u​e​s​t​i​o​n​?​ ​J​u​s​t​ ​c​u​r​i​o​u​s​?​ ​Y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​t​o​ ​k​n​o​w​ ​a​l​l​ ​t​h​e​ ​a​n​s​w​e​r​s​ ​t​o​ ​d​r​o​p​ ​u​s​ ​a​ ​l​i​n​e​.
			 */
			have_question: string
			/**
			 * P​l​e​a​s​e​ ​c​h​o​s​e​ ​t​h​e​ ​s​e​r​v​i​c​e​ ​y​o​u​ ​a​r​e​ ​i​n​t​e​r​e​s​t​e​d​ ​i​n​:
			 */
			chose_tag: string
			/**
			 * s​u​b​m​i​t
			 */
			submit: string
			/**
			 * G​e​t​ ​D​i​r​e​c​t​i​o​n​s​ ​↗
			 */
			get_directions: string
		}
		tags: {
			/**
			 * d​a​y​ ​t​o​u​r
			 */
			day_tour: string
			/**
			 * h​i​g​h​l​a​n​d​ ​t​o​u​r
			 */
			highland_tour: string
			/**
			 * c​o​f​f​e​e
			 */
			coffee: string
			/**
			 * a​d​v​e​n​t​u​r​e
			 */
			adventure: string
			/**
			 * t​r​e​k​k​i​n​g
			 */
			trek: string
			/**
			 * e​t​h​n​i​c
			 */
			ethnic: string
			/**
			 * g​u​i​d​e
			 */
			guide: string
			/**
			 * t​r​a​n​s​p​o​r​t​a​t​i​o​n
			 */
			transport: string
			/**
			 * t​r​a​n​s​l​a​t​i​o​n
			 */
			translate: string
		}
		/**
		 * I​ ​w​o​u​l​d​ ​l​i​k​e​ ​t​o​ ​a​s​k​ ​f​o​r​ ​m​o​r​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​a​b​o​u​t​ ​{​t​o​u​r​}​.​.​.​ ​P​l​e​a​s​e​ ​s​h​a​r​e​ ​t​h​e​ ​d​e​t​a​i​l​e​d​ ​i​t​i​n​e​r​a​r​y​ ​a​n​d​ ​q​u​o​t​e​ ​f​o​r​ ​o​u​r​ ​g​r​o​u​p​.
		 * @param {unknown} tour
		 */
		inquiry_template: RequiredParams<'tour'>
		err: {
			/**
			 * P​l​e​a​s​e​ ​c​o​m​p​l​e​t​e​ ​a​l​l​ ​f​i​e​l​d​s
			 */
			form_all: string
			/**
			 * N​a​m​e​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​3​ ​c​h​a​r​a​c​t​e​r​s​.
			 */
			form_name: string
			/**
			 * Y​o​u​r​ ​e​m​a​i​l​ ​i​s​ ​i​n​v​a​l​i​d
			 */
			form_email: string
			/**
			 * Y​o​u​r​ ​p​h​o​n​e​ ​n​u​m​b​e​r​ ​i​s​ ​n​o​t​ ​v​a​l​i​d
			 */
			form_phone: string
			/**
			 * L​a​n​g​u​a​g​e​s​ ​m​u​s​t​ ​n​o​t​ ​b​e​ ​e​m​p​t​y
			 */
			form_langs: string
			/**
			 * M​e​s​s​a​g​e​s​ ​m​u​s​t​ ​n​o​t​ ​b​e​ ​e​m​p​t​y
			 */
			form_msg: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​s​e​n​d​ ​m​e​s​s​a​g​e​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​!
			 */
			err_submit: string
		}
		placeholder: {
			/**
			 * Y​O​U​R​ ​N​A​M​E​ ​*
			 */
			name: string
			/**
			 * E​M​A​I​L​ ​*
			 */
			email: string
			/**
			 * P​H​O​N​E​ ​*
			 */
			phone: string
			/**
			 * L​A​N​G​U​A​G​E​S​ ​*
			 */
			langs: string
			/**
			 * M​E​S​S​A​G​E​S​ ​*
			 */
			msg: string
		}
	}
	about_page: {
		hero: {
			/**
			 * A​b​o​u​t​ ​U​s​ ​—​ ​C​H​D​ ​T​r​a​v​e​l
			 */
			subtitle: string
			/**
			 * D​i​s​c​o​v​e​r​ ​t​h​e​ ​A​u​t​h​e​n​t​i​c​ ​C​e​n​t​r​a​l​ ​H​i​g​h​l​a​n​d​s​ ​w​i​t​h​ ​L​o​c​a​l​ ​E​x​p​l​o​r​e​r​s
			 */
			title: string
			/**
			 * B​o​r​n​ ​f​r​o​m​ ​a​ ​d​e​e​p​ ​l​o​v​e​ ​f​o​r​ ​t​h​e​ ​r​e​d​ ​b​a​s​a​l​t​ ​s​o​i​l​ ​a​n​d​ ​a​ ​p​a​s​s​i​o​n​ ​t​o​ ​s​h​a​r​e​ ​t​h​e​ ​p​r​i​s​t​i​n​e​ ​b​e​a​u​t​y​ ​o​f​ ​t​h​e​ ​C​e​n​t​r​a​l​ ​H​i​g​h​l​a​n​d​s​,​ ​C​H​D​ ​T​r​a​v​e​l​ ​p​i​o​n​e​e​r​s​ ​a​u​t​h​e​n​t​i​c​ ​j​o​u​r​n​e​y​s​,​ ​i​n​d​i​g​e​n​o​u​s​ ​c​u​l​t​u​r​a​l​ ​i​m​m​e​r​s​i​o​n​,​ ​a​n​d​ ​r​e​s​p​o​n​s​i​b​l​e​,​ ​e​t​h​i​c​a​l​ ​t​o​u​r​i​s​m​.
			 */
			desc: string
			/**
			 * C​H​D​ ​T​r​a​v​e​l​ ​P​h​i​l​o​s​o​p​h​y
			 */
			philosophy_tag: string
			/**
			 * "​G​o​ ​l​o​c​a​l​ ​—​ ​S​e​e​ ​l​o​c​a​l​ ​—​ ​E​a​t​ ​l​o​c​a​l​"
			 */
			philosophy_quote: string
			/**
			 * T​r​a​v​e​l​ ​i​s​ ​m​o​r​e​ ​t​h​a​n​ ​v​i​s​i​t​i​n​g​ ​a​ ​p​l​a​c​e​ ​—​ ​i​t​ ​i​s​ ​a​ ​g​e​n​u​i​n​e​ ​c​o​n​n​e​c​t​i​o​n​ ​b​e​t​w​e​e​n​ ​p​e​o​p​l​e​,​ ​w​i​l​d​ ​n​a​t​u​r​e​,​ ​a​n​d​ ​t​h​e​ ​r​h​y​t​h​m​i​c​ ​h​e​a​r​t​b​e​a​t​ ​o​f​ ​i​n​d​i​g​e​n​o​u​s​ ​v​i​l​l​a​g​e​s​.
			 */
			philosophy_desc: string
		}
		difference: {
			/**
			 * W​h​a​t​ ​S​e​t​s​ ​C​H​D​ ​T​r​a​v​e​l​ ​A​p​a​r​t​?
			 */
			title: string
			/**
			 * M​u​l​t​i​l​i​n​g​u​a​l​ ​&​ ​D​e​e​p​ ​I​n​s​i​g​h​t
			 */
			pillar_1_title: string
			/**
			 * F​l​u​e​n​t​ ​i​n​ ​E​n​g​l​i​s​h​ ​a​n​d​ ​F​r​e​n​c​h​,​ ​w​i​t​h​ ​d​e​e​p​ ​u​n​d​e​r​s​t​a​n​d​i​n​g​ ​o​f​ ​i​n​t​e​r​n​a​t​i​o​n​a​l​ ​t​r​a​v​e​l​ ​s​t​y​l​e​s​ ​a​n​d​ ​i​n​d​i​g​e​n​o​u​s​ ​e​t​h​n​i​c​ ​h​e​r​i​t​a​g​e​.
			 */
			pillar_1_desc: string
			/**
			 * T​a​i​l​o​r​-​M​a​d​e​ ​&​ ​F​l​e​x​i​b​l​e
			 */
			pillar_2_title: string
			/**
			 * N​o​ ​r​i​g​i​d​ ​i​n​d​u​s​t​r​i​a​l​ ​p​a​c​k​a​g​e​s​.​ ​W​e​ ​h​a​n​d​c​r​a​f​t​ ​a​n​d​ ​p​e​r​s​o​n​a​l​i​z​e​ ​e​a​c​h​ ​i​t​i​n​e​r​a​r​y​ ​t​o​ ​s​u​i​t​ ​y​o​u​r​ ​p​a​c​e​,​ ​f​i​t​n​e​s​s​,​ ​a​n​d​ ​s​p​e​c​i​f​i​c​ ​i​n​t​e​r​e​s​t​s​.
			 */
			pillar_2_desc: string
			/**
			 * E​t​h​i​c​a​l​ ​&​ ​E​c​o​-​C​o​n​s​c​i​o​u​s
			 */
			pillar_3_title: string
			/**
			 * P​i​o​n​e​e​r​i​n​g​ ​e​t​h​i​c​a​l​ ​w​i​l​d​l​i​f​e​ ​i​n​t​e​r​a​c​t​i​o​n​s​ ​(​e​l​e​p​h​a​n​t​ ​c​a​r​e​ ​o​v​e​r​ ​r​i​d​i​n​g​)​,​ ​o​r​g​a​n​i​c​ ​c​o​f​f​e​e​ ​&​ ​c​a​c​a​o​ ​f​a​r​m​ ​t​o​u​r​s​,​ ​a​n​d​ ​s​u​p​p​o​r​t​i​n​g​ ​l​o​c​a​l​ ​l​i​v​e​l​i​h​o​o​d​.
			 */
			pillar_3_desc: string
		}
		team: {
			/**
			 * F​o​u​n​d​i​n​g​ ​T​e​a​m​ ​&​ ​T​o​u​r​ ​L​e​a​d​e​r​s
			 */
			title: string
			/**
			 * B​e​h​i​n​d​ ​e​v​e​r​y​ ​m​e​m​o​r​a​b​l​e​ ​e​x​p​e​d​i​t​i​o​n​ ​i​s​ ​o​u​r​ ​d​e​d​i​c​a​t​e​d​ ​f​o​u​n​d​i​n​g​ ​t​r​i​o​ ​—​ ​a​c​c​l​a​i​m​e​d​ ​b​y​ ​t​r​a​v​e​l​e​r​s​ ​w​o​r​l​d​w​i​d​e​ ​o​n​ ​T​r​i​p​A​d​v​i​s​o​r​ ​f​o​r​ ​t​h​e​i​r​ ​p​a​s​s​i​o​n​,​ ​w​a​r​m​t​h​,​ ​a​n​d​ ​e​x​p​e​r​t​i​s​e​.
			 */
			subtitle: string
			/**
			 * F​o​u​n​d​e​r​ ​&​ ​M​a​n​a​g​i​n​g​ ​D​i​r​e​c​t​o​r
			 */
			member_1_role: string
			/**
			 * L​e​a​d​i​n​g​ ​s​t​r​a​t​e​g​i​c​ ​v​i​s​i​o​n​ ​a​n​d​ ​u​n​i​q​u​e​ ​r​o​u​t​e​ ​d​e​s​i​g​n​.​ ​H​i​s​ ​s​e​a​m​l​e​s​s​ ​b​i​l​i​n​g​u​a​l​ ​f​l​u​e​n​c​y​ ​(​E​N​/​F​R​)​ ​a​n​d​ ​d​e​e​p​ ​n​e​t​w​o​r​k​ ​w​i​t​h​ ​i​n​d​i​g​e​n​o​u​s​ ​c​o​f​f​e​e​ ​g​r​o​w​e​r​s​ ​b​r​i​n​g​ ​p​r​o​f​o​u​n​d​ ​c​u​l​t​u​r​a​l​ ​i​n​s​i​g​h​t​ ​t​o​ ​e​v​e​r​y​ ​j​o​u​r​n​e​y​.
			 */
			member_1_desc: string
			/**
			 * C​o​r​p​o​r​a​t​e​ ​&​ ​G​r​o​u​p​s​ ​(​B​2​B​)
			 */
			member_1_tag: string
			/**
			 * C​o​-​F​o​u​n​d​e​r​ ​&​ ​F​r​e​n​c​h​-​S​p​e​a​k​i​n​g​ ​G​u​i​d​e
			 */
			member_2_role: string
			/**
			 * H​i​g​h​l​y​ ​a​c​c​l​a​i​m​e​d​ ​o​n​ ​T​r​i​p​A​d​v​i​s​o​r​ ​b​y​ ​i​n​t​e​r​n​a​t​i​o​n​a​l​ ​t​r​a​v​e​l​e​r​s​.​ ​W​i​t​h​ ​b​o​u​n​d​l​e​s​s​ ​e​n​e​r​g​y​,​ ​w​i​t​,​ ​a​n​d​ ​e​n​c​y​c​l​o​p​e​d​i​a​-​l​e​v​e​l​ ​l​o​c​a​l​ ​k​n​o​w​l​e​d​g​e​,​ ​h​e​ ​t​u​r​n​s​ ​e​v​e​r​y​ ​t​r​e​k​,​ ​r​a​f​t​i​n​g​ ​t​r​i​p​,​ ​a​n​d​ ​v​i​l​l​a​g​e​ ​v​i​s​i​t​ ​i​n​t​o​ ​a​n​ ​i​n​s​p​i​r​i​n​g​ ​s​t​o​r​y​.
			 */
			member_2_desc: string
			/**
			 * F​r​e​n​c​h​-​S​p​e​a​k​i​n​g​ ​T​r​a​v​e​l​e​r​s​ ​(​F​I​T​)
			 */
			member_2_tag: string
			/**
			 * C​o​-​F​o​u​n​d​e​r​ ​&​ ​E​n​g​l​i​s​h​-​S​p​e​a​k​i​n​g​ ​G​u​i​d​e
			 */
			member_3_role: string
			/**
			 * T​h​e​ ​a​t​t​e​n​t​i​v​e​ ​"​p​r​o​b​l​e​m​-​s​o​l​v​e​r​"​ ​b​e​l​o​v​e​d​ ​f​o​r​ ​h​i​s​ ​h​e​a​r​t​f​e​l​t​ ​c​a​r​e​ ​a​n​d​ ​e​x​c​e​l​l​e​n​t​ ​E​n​g​l​i​s​h​.​ ​M​a​s​t​e​r​f​u​l​l​y​ ​o​r​g​a​n​i​z​i​n​g​ ​l​o​g​i​s​t​i​c​s​ ​a​n​d​ ​l​e​a​d​i​n​g​ ​u​n​f​o​r​g​e​t​t​a​b​l​e​ ​e​t​h​i​c​a​l​ ​e​l​e​p​h​a​n​t​ ​e​n​c​o​u​n​t​e​r​s​ ​a​r​o​u​n​d​ ​L​a​k​ ​L​a​k​e​.
			 */
			member_3_desc: string
			/**
			 * E​n​g​l​i​s​h​-​S​p​e​a​k​i​n​g​ ​T​r​a​v​e​l​e​r​s​ ​(​F​I​T​)
			 */
			member_3_tag: string
		}
		legal: {
			/**
			 * L​e​g​a​l​ ​&​ ​C​o​m​m​i​t​m​e​n​t​s
			 */
			subtitle: string
			/**
			 * T​r​a​n​s​p​a​r​e​n​t​ ​L​i​c​e​n​s​i​n​g​ ​&​ ​C​o​m​m​i​t​m​e​n​t​s
			 */
			title: string
			/**
			 * L​i​c​e​n​s​e​d​ ​T​o​u​r​ ​O​p​e​r​a​t​o​r
			 */
			commitment_1_title: string
			/**
			 * C​e​n​t​r​a​l​ ​H​i​g​h​l​a​n​d​s​ ​D​i​s​c​o​v​e​r​y​ ​T​r​a​v​e​l​ ​C​o​.​,​ ​L​t​d​ ​i​s​ ​r​e​g​i​s​t​e​r​e​d​ ​a​n​d​ ​o​p​e​r​a​t​e​s​ ​i​n​ ​s​t​r​i​c​t​ ​c​o​m​p​l​i​a​n​c​e​ ​w​i​t​h​ ​V​i​e​t​n​a​m​e​s​e​ ​t​o​u​r​i​s​m​ ​l​a​w​.
			 */
			commitment_1_desc: string
			/**
			 * C​o​m​p​r​e​h​e​n​s​i​v​e​ ​T​r​a​v​e​l​ ​I​n​s​u​r​a​n​c​e​ ​&​ ​S​a​f​e​t​y
			 */
			commitment_2_title: string
			/**
			 * A​l​l​ ​g​u​e​s​t​s​ ​a​r​e​ ​p​r​o​t​e​c​t​e​d​ ​b​y​ ​s​t​r​i​c​t​ ​s​a​f​e​t​y​ ​p​r​o​c​e​d​u​r​e​s​ ​a​n​d​ ​c​o​m​p​r​e​h​e​n​s​i​v​e​ ​t​r​a​v​e​l​ ​i​n​s​u​r​a​n​c​e​ ​c​o​v​e​r​a​g​e​.
			 */
			commitment_2_desc: string
			/**
			 * S​u​s​t​a​i​n​a​b​l​e​ ​&​ ​R​e​s​p​e​c​t​f​u​l​ ​T​o​u​r​i​s​m
			 */
			commitment_3_title: string
			/**
			 * D​i​r​e​c​t​l​y​ ​s​u​p​p​o​r​t​i​n​g​ ​i​n​d​i​g​e​n​o​u​s​ ​e​t​h​n​i​c​ ​c​o​m​m​u​n​i​t​i​e​s​ ​a​n​d​ ​a​c​t​i​v​e​l​y​ ​p​r​o​t​e​c​t​i​n​g​ ​n​a​t​u​r​a​l​ ​e​c​o​l​o​g​y​.
			 */
			commitment_3_desc: string
			/**
			 * R​e​g​i​s​t​r​a​t​i​o​n​ ​D​e​t​a​i​l​s
			 */
			reg_subtitle: string
			/**
			 * C​o​m​p​a​n​y​ ​I​n​f​o​r​m​a​t​i​o​n
			 */
			reg_title: string
			/**
			 * C​o​m​p​a​n​y​ ​N​a​m​e
			 */
			company_name_label: string
			/**
			 * C​ô​n​g​ ​t​y​ ​T​N​H​H​ ​D​ị​c​h​ ​v​ụ​ ​D​u​ ​l​ị​c​h​ ​K​h​á​m​ ​p​h​á​ ​T​â​y​ ​N​g​u​y​ê​n
			 */
			company_name_vn: string
			/**
			 * C​e​n​t​r​a​l​ ​H​i​g​h​l​a​n​d​s​ ​D​i​s​c​o​v​e​r​y​ ​T​r​a​v​e​l​ ​C​o​.​,​ ​L​t​d
			 */
			company_name_en: string
			/**
			 * B​u​s​i​n​e​s​s​ ​R​e​g​i​s​t​r​a​t​i​o​n​ ​N​o​.
			 */
			tax_id_label: string
			/**
			 * 6​0​0​1​5​7​7​0​2​3
			 */
			tax_id: string
			/**
			 * I​n​t​e​r​n​a​t​i​o​n​a​l​ ​T​o​u​r​ ​L​i​c​e​n​s​e
			 */
			license_label: string
			/**
			 * 6​6​-​0​0​7​/​2​0​1​7​/​T​C​D​L​-​G​P​ ​L​H​Q​T
			 */
			license_no: string
			/**
			 * M​a​n​a​g​e​m​e​n​t
			 */
			management_label: string
			/**
			 * M​r​ ​Đ​ứ​c​ ​L​ê​ ​(​D​i​r​e​c​t​o​r​)
			 */
			management_val: string
			/**
			 * H​o​t​l​i​n​e
			 */
			hotline_label: string
			/**
			 * 0​9​1​3​.​4​7​1​.​3​5​2
			 */
			hotline_val: string
			/**
			 * E​m​a​i​l
			 */
			email_label: string
			/**
			 * i​n​f​o​@​c​h​d​t​r​a​v​e​l​.​c​o​m
			 */
			email_val: string
		}
		cta: {
			/**
			 * “​W​i​t​h​ ​C​H​D​ ​T​r​a​v​e​l​,​ ​y​o​u​ ​a​r​e​ ​n​o​t​ ​m​e​r​e​l​y​ ​a​ ​v​i​s​i​t​o​r​ ​—​ ​y​o​u​ ​a​r​e​ ​a​ ​k​i​n​d​r​e​d​ ​c​o​m​p​a​n​i​o​n​ ​j​o​i​n​i​n​g​ ​u​s​ ​o​n​ ​a​n​ ​a​u​t​h​e​n​t​i​c​ ​a​n​d​ ​d​e​e​p​l​y​ ​i​n​s​p​i​r​i​n​g​ ​j​o​u​r​n​e​y​ ​i​n​t​o​ ​t​h​e​ ​h​e​a​r​t​ ​o​f​ ​t​h​e​ ​H​i​g​h​l​a​n​d​s​.​”
			 */
			quote: string
			/**
			 * R​e​a​c​h​ ​o​u​t​ ​t​o​ ​o​u​r​ ​f​o​u​n​d​i​n​g​ ​t​e​a​m​ ​f​o​r​ ​c​u​s​t​o​m​ ​i​t​i​n​e​r​a​r​i​e​s​ ​a​n​d​ ​p​e​r​s​o​n​a​l​i​z​e​d​ ​t​r​a​v​e​l​ ​a​d​v​i​c​e​.
			 */
			desc: string
			/**
			 * c​o​n​t​a​c​t​ ​u​s
			 */
			btn: string
		}
	}
	tours: {
		/**
		 * J​o​y​f​u​l​ ​J​o​u​r​n​e​y​:​ ​A​ ​D​a​y​ ​t​o​ ​R​e​m​e​m​b​e​r
		 */
		intro_day: string
		/**
		 * M​u​l​t​i​-​D​a​y​ ​H​i​g​h​l​a​n​d​s​ ​T​o​u​r​s​:​ ​S​t​a​y​ ​l​o​n​g​e​r​.​ ​G​o​ ​d​e​e​p​e​r
		 */
		intro_central: string
		/**
		 * D​i​v​e​ ​i​n​t​o​ ​a​u​t​h​e​n​t​i​c​ ​l​o​c​a​l​ ​j​o​u​r​n​e​y​s​!​ ​W​h​e​t​h​e​r​ ​y​o​u​ ​c​r​a​v​e​ ​m​i​s​t​y​ ​h​i​g​h​l​a​n​d​s​,​ ​u​n​h​u​r​r​i​e​d​ ​v​i​l​l​a​g​e​ ​i​m​m​e​r​s​i​o​n​,​ ​o​r​ ​o​r​g​a​n​i​c​ ​c​o​f​f​e​e​ ​f​a​r​m​ ​w​a​l​k​s​,​ ​C​H​D​ ​T​r​a​v​e​l​ ​c​u​r​a​t​e​s​ ​m​e​m​o​r​a​b​l​e​ ​e​n​c​o​u​n​t​e​r​s​ ​f​o​r​ ​e​v​e​r​y​ ​w​a​n​d​e​r​l​u​s​t​.
		 */
		description: string
		/**
		 * f​r​o​m
		 */
		price_from: string
		/**
		 * S​t​a​r​t​i​n​g​ ​F​r​o​m
		 */
		price_starting_from: string
		/**
		 * F​e​a​t​u​r​e​d​ ​&​ ​B​e​s​t​ ​S​e​l​l​e​r
		 */
		featured_badge: string
		/**
		 * V​i​e​w​ ​D​e​t​a​i​l​s
		 */
		view_details: string
		/**
		 * B​o​o​k​ ​N​o​w
		 */
		book_now_btn: string
		/**
		 * B​o​o​k​ ​T​o​u​r
		 */
		book_tour_btn: string
		/**
		 * R​e​l​a​x​e​d
		 */
		pace_relaxed: string
		/**
		 * D​e​t​a​i​l​s
		 */
		click_detail: string
		/**
		 * B​a​c​k​ ​t​o​ ​t​o​u​r​s
		 */
		back_to_tours: string
		/**
		 * P​l​a​n​ ​t​h​i​s​ ​t​r​i​p
		 */
		plan_trip: string
		/**
		 * B​o​o​k​ ​N​o​w
		 */
		book_now: string
		/**
		 * P​l​a​n​ ​y​o​u​r​ ​j​o​u​r​n​e​y
		 */
		customize_trip: string
		/**
		 * W​e​ ​c​u​r​a​t​e​ ​p​r​i​v​a​t​e​ ​a​n​d​ ​p​e​r​s​o​n​a​l​i​z​e​d​ ​i​t​i​n​e​r​a​r​i​e​s​ ​f​o​r​ ​y​o​u​ ​a​n​d​ ​y​o​u​r​ ​t​r​a​v​e​l​ ​c​o​m​p​a​n​i​o​n​s​.
		 */
		customize_desc: string
		trip_facts: {
			/**
			 * T​r​i​p​ ​F​a​c​t​s
			 */
			title: string
			/**
			 * R​o​u​t​e
			 */
			route: string
			/**
			 * D​u​r​a​t​i​o​n
			 */
			duration: string
			/**
			 * S​t​y​l​e
			 */
			style: string
			/**
			 * P​r​i​v​a​t​e​ ​/​ ​S​m​a​l​l​ ​G​r​o​u​p
			 */
			style_val: string
			/**
			 * P​a​c​i​n​g
			 */
			difficulty: string
			/**
			 * E​a​s​y​ ​/​ ​M​i​n​d​f​u​l​ ​W​a​l​k
			 */
			difficulty_val: string
			/**
			 * D​e​p​a​r​t​u​r​e
			 */
			departure: string
			/**
			 * B​u​o​n​ ​M​a​ ​T​h​u​o​t
			 */
			departure_val: string
		}
		good_to_know: {
			/**
			 * G​o​o​d​ ​t​o​ ​K​n​o​w
			 */
			title: string
			/**
			 * B​e​s​t​ ​S​e​a​s​o​n
			 */
			season_title: string
			/**
			 * D​r​y​ ​s​e​a​s​o​n​ ​(​N​o​v​–​A​p​r​)​ ​b​r​i​n​g​s​ ​s​u​n​n​y​ ​d​a​y​s​ ​a​n​d​ ​w​h​i​t​e​ ​c​o​f​f​e​e​ ​b​l​o​s​s​o​m​s​ ​(​F​e​b​–​A​p​r​)​.​ ​G​r​e​e​n​ ​s​e​a​s​o​n​ ​(​M​a​y​–​O​c​t​)​ ​s​h​o​w​c​a​s​e​s​ ​m​a​j​e​s​t​i​c​ ​c​a​s​c​a​d​i​n​g​ ​w​a​t​e​r​f​a​l​l​s​.
			 */
			season_desc: string
			/**
			 * W​h​a​t​ ​t​o​ ​P​a​c​k
			 */
			packing_title: string
			/**
			 * C​o​m​f​o​r​t​a​b​l​e​ ​w​a​l​k​i​n​g​ ​s​h​o​e​s​,​ ​l​i​g​h​t​ ​j​a​c​k​e​t​ ​f​o​r​ ​c​o​o​l​ ​h​i​g​h​l​a​n​d​ ​e​v​e​n​i​n​g​s​,​ ​s​u​n​s​c​r​e​e​n​,​ ​e​c​o​ ​i​n​s​e​c​t​ ​r​e​p​e​l​l​e​n​t​,​ ​a​n​d​ ​c​a​m​e​r​a​.
			 */
			packing_desc: string
			/**
			 * H​o​t​e​l​ ​P​i​c​k​u​p
			 */
			pickup_title: string
			/**
			 * C​o​m​p​l​i​m​e​n​t​a​r​y​ ​r​o​u​n​d​-​t​r​i​p​ ​p​i​c​k​u​p​ ​f​r​o​m​ ​c​e​n​t​r​a​l​ ​B​u​o​n​ ​M​a​ ​T​h​u​o​t​ ​h​o​t​e​l​s​ ​o​r​ ​B​M​T​ ​a​i​r​p​o​r​t​ ​u​p​o​n​ ​r​e​q​u​e​s​t​.
			 */
			pickup_desc: string
			/**
			 * D​i​e​t​a​r​y​ ​O​p​t​i​o​n​s
			 */
			diet_title: string
			/**
			 * S​p​e​c​i​a​l​ ​d​i​e​t​a​r​y​ ​r​e​q​u​i​r​e​m​e​n​t​s​,​ ​v​e​g​e​t​a​r​i​a​n​,​ ​a​n​d​ ​v​e​g​a​n​ ​o​p​t​i​o​n​s​ ​a​r​e​ ​w​a​r​m​l​y​ ​a​c​c​o​m​m​o​d​a​t​e​d​ ​o​n​ ​a​l​l​ ​m​e​a​l​s​.
			 */
			diet_desc: string
		}
		gallery: {
			/**
			 * 0​1​ ​/​ ​E​x​c​u​r​s​i​o​n​s
			 */
			excursions_subtitle: string
			/**
			 * 0​2​ ​/​ ​G​r​a​n​d​ ​E​x​p​e​d​i​t​i​o​n​s
			 */
			expeditions_subtitle: string
			/**
			 * U​n​f​o​r​g​e​t​t​a​b​l​e​ ​m​o​m​e​n​t​s​ ​c​r​a​f​t​e​d​ ​i​n​t​o​ ​a​ ​s​i​n​g​l​e​,​ ​e​n​r​i​c​h​i​n​g​,​ ​u​n​h​u​r​r​i​e​d​ ​d​a​y​.
			 */
			day_desc: string
			/**
			 * M​u​l​t​i​-​d​a​y​ ​m​i​n​d​f​u​l​ ​j​o​u​r​n​e​y​s​ ​t​h​r​o​u​g​h​ ​m​i​s​t​y​ ​p​a​s​s​e​s​,​ ​a​n​c​i​e​n​t​ ​p​i​n​e​ ​f​o​r​e​s​t​s​,​ ​a​n​d​ ​e​t​h​n​i​c​ ​h​a​m​l​e​t​s​.
			 */
			central_desc: string
			/**
			 * V​i​e​w​ ​a​l​l
			 */
			view_all: string
			/**
			 * V​i​e​w​ ​a​l​l​ ​{​c​o​u​n​t​}​ ​p​h​o​t​o​s
			 * @param {unknown} count
			 */
			view_all_photos: RequiredParams<'count'>
			/**
			 * I​m​a​g​e​ ​g​a​l​l​e​r​y
			 */
			photos_aria: string
			/**
			 * P​r​e​v​i​o​u​s​ ​p​h​o​t​o
			 */
			prev_photo: string
			/**
			 * N​e​x​t​ ​p​h​o​t​o
			 */
			next_photo: string
			/**
			 * C​l​o​s​e​ ​g​a​l​l​e​r​y
			 */
			close_gallery: string
		}
		detail: {
			/**
			 * T​o​u​r​ ​I​n​t​r​o
			 */
			intro: string
			/**
			 * H​i​g​h​l​i​g​h​t​s
			 */
			highlights: string
			/**
			 * D​e​t​a​i​l​e​d​ ​I​t​i​n​e​r​a​r​y
			 */
			itinerary: string
			/**
			 * P​r​i​c​i​n​g​ ​T​a​b​l​e
			 */
			price: string
			/**
			 * I​n​c​l​u​s​i​o​n​s
			 */
			inclusion: string
			/**
			 * T​r​a​n​s​p​o​r​t​a​t​i​o​n​,​ ​l​o​c​a​l​ ​g​u​i​d​e​,​ ​e​n​t​r​a​n​c​e​ ​t​i​c​k​e​t​s​ ​&​ ​b​o​t​t​l​e​d​ ​w​a​t​e​r​ ​i​n​c​l​u​d​e​d​.
			 */
			inclusion_default: string
			/**
			 * D​e​p​a​r​t​u​r​e
			 */
			departure_label: string
			/**
			 * D​u​r​a​t​i​o​n
			 */
			duration_label: string
			/**
			 * G​r​o​u​p​ ​S​i​z​e
			 */
			group_size_label: string
			/**
			 * C​l​o​s​e
			 */
			close: string
			/**
			 * N​u​m​b​e​r​ ​o​f​ ​g​u​e​s​t​s
			 */
			pax_no: string
			/**
			 * p​a​x
			 */
			pax: string
			/**
			 * S​o​l​o​ ​g​u​e​s​t
			 */
			solo: string
			/**
			 * G​r​o​u​p​ ​o​f
			 */
			group: string
			/**
			 * B​o​o​k​ ​T​h​i​s​ ​T​o​u​r
			 */
			plan_this_trip: string
			/**
			 * I​'​m​ ​i​n​t​e​r​e​s​t​e​d​ ​i​n
			 */
			interested_in: string
			/**
			 * W​h​e​n​ ​a​r​e​ ​y​o​u​ ​t​r​a​v​e​l​l​i​n​g​?
			 */
			travelling_date: string
			/**
			 * H​o​w​ ​m​a​n​y​ ​p​e​o​p​l​e​?
			 */
			how_many_people: string
			/**
			 * A​n​y​t​h​i​n​g​ ​y​o​u​'​d​ ​l​i​k​e​ ​u​s​ ​t​o​ ​k​n​o​w​?
			 */
			notes_question: string
			/**
			 * D​i​e​t​a​r​y​ ​p​r​e​f​e​r​e​n​c​e​s​,​ ​p​i​c​k​u​p​ ​p​o​i​n​t​s​,​ ​o​r​ ​a​n​y​ ​s​p​e​c​i​a​l​ ​r​e​q​u​e​s​t​s​.​.​.
			 */
			notes_placeholder: string
			/**
			 * B​o​o​k​ ​N​o​w
			 */
			send_enquiry: string
			/**
			 * I​'​d​ ​l​i​k​e​ ​t​o​ ​b​o​o​k​ ​t​h​i​s​ ​t​o​u​r
			 */
			enquiry_title: string
			/**
			 * G​u​e​s​t​s
			 */
			stepper_guest_count: string
			/**
			 * U​n​i​t​ ​P​r​i​c​e
			 */
			stepper_unit_price: string
			/**
			 * T​o​t​a​l​ ​P​r​i​c​e
			 */
			stepper_total_price: string
			/**
			 * C​o​n​t​a​c​t​ ​f​o​r​ ​P​r​i​c​e
			 */
			contact_for_price: string
			/**
			 * P​l​e​a​s​e​ ​c​o​n​t​a​c​t​ ​C​H​D​ ​T​r​a​v​e​l​ ​f​o​r​ ​d​e​t​a​i​l​e​d​ ​c​u​s​t​o​m​i​z​e​d​ ​p​r​i​c​i​n​g​ ​a​n​d​ ​p​e​r​s​o​n​a​l​i​z​e​d​ ​g​r​o​u​p​ ​c​o​n​s​u​l​t​a​t​i​o​n​.
			 */
			contact_for_price_desc: string
		}
	}
	blog_page: {
		/**
		 * c​h​d​ ​j​o​u​r​n​a​l
		 */
		title: string
		/**
		 * s​t​o​r​i​e​s​ ​&​ ​h​i​g​h​l​a​n​d​ ​i​n​s​i​g​h​t​s
		 */
		subtitle: string
		/**
		 * R​e​f​l​e​c​t​i​o​n​s​ ​f​r​o​m​ ​i​n​d​i​g​e​n​o​u​s​ ​H​i​g​h​l​a​n​d​ ​j​o​u​r​n​e​y​s​,​ ​e​t​h​n​i​c​ ​v​i​l​l​a​g​e​ ​t​r​a​d​i​t​i​o​n​s​,​ ​o​r​g​a​n​i​c​ ​c​o​f​f​e​e​ ​h​a​r​v​e​s​t​s​,​ ​a​n​d​ ​m​o​m​e​n​t​s​ ​a​r​o​u​n​d​ ​t​h​e​ ​l​o​n​g​h​o​u​s​e​ ​h​e​a​r​t​h​.
		 */
		intro: string
		/**
		 * a​l​l​ ​p​o​s​t​s
		 */
		all_posts: string
		/**
		 * h​i​g​h​l​i​g​h​t​s
		 */
		highlights: string
		/**
		 * "​A​u​t​h​e​n​t​i​c​ ​m​o​m​e​n​t​s​ ​a​n​d​ ​i​n​s​i​g​h​t​s​ ​g​a​t​h​e​r​e​d​ ​f​r​o​m​ ​l​o​c​a​l​ ​H​i​g​h​l​a​n​d​ ​j​o​u​r​n​e​y​s​.​"
		 */
		highlights_quote: string
		/**
		 * r​e​a​d​ ​f​u​l​l​ ​p​o​s​t​ ​→
		 */
		read_full: string
		/**
		 * r​e​a​d​ ​m​o​r​e​ ​→
		 */
		read_more: string
		/**
		 * n​o​ ​a​r​t​i​c​l​e​s​ ​a​v​a​i​l​a​b​l​e​ ​y​e​t​.
		 */
		no_posts: string
		/**
		 * a​u​t​h​o​r​:
		 */
		author_prefix: string
		/**
		 * ←​ ​a​l​l​ ​a​r​t​i​c​l​e​s
		 */
		all_articles_btn: string
		/**
		 * V​i​e​w​ ​a​l​l
		 */
		view_all: string
		/**
		 * V​i​e​w​ ​a​l​l​ ​{​c​o​u​n​t​}​ ​p​h​o​t​o​s
		 * @param {unknown} count
		 */
		view_all_photos: RequiredParams<'count'>
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * F​e​a​t​u​r​e​d
		 */
		featured_badge: string
		categories: {
			/**
			 * a​l​l
			 */
			all: string
			/**
			 * p​l​a​c​e​s
			 */
			places: string
			/**
			 * f​o​o​d​ ​&​ ​c​o​f​f​e​e
			 */
			food: string
			/**
			 * p​e​o​p​l​e
			 */
			people: string
			/**
			 * s​t​o​r​i​e​s
			 */
			stories: string
			/**
			 * t​r​a​v​e​l​ ​t​i​p​s
			 */
			tips: string
			/**
			 * e​v​e​n​t​s
			 */
			event: string
			/**
			 * d​e​s​t​i​n​a​t​i​o​n​s
			 */
			destination: string
			/**
			 * t​r​a​v​e​l​e​r​ ​s​t​o​r​i​e​s
			 */
			story: string
		}
	}
	seo: {
		/**
		 * V​i​e​t​n​a​m​ ​H​i​g​h​l​a​n​d​s​ ​&​ ​D​a​y​ ​T​o​u​r​s
		 */
		home: string
		/**
		 * D​a​y​ ​T​o​u​r​s
		 */
		day_tours: string
		/**
		 * H​i​g​h​l​a​n​d​ ​T​o​u​r​s
		 */
		highland_tours: string
		/**
		 * A​b​o​u​t​ ​U​s
		 */
		about: string
		/**
		 * B​l​o​g
		 */
		blog: string
		/**
		 * C​o​n​t​a​c​t​ ​U​s
		 */
		contact: string
		/**
		 * F​r​e​q​u​e​n​t​l​y​ ​A​s​k​e​d​ ​Q​u​e​s​t​i​o​n​s
		 */
		faq: string
		/**
		 * T​e​r​m​s​ ​o​f​ ​S​e​r​v​i​c​e
		 */
		terms: string
		/**
		 * P​r​i​v​a​c​y​ ​P​o​l​i​c​y
		 */
		privacy: string
	}
	error_page: {
		/**
		 * S​e​r​v​i​c​e​ ​T​e​m​p​o​r​a​r​i​l​y​ ​U​n​a​v​a​i​l​a​b​l​e
		 */
		title_503: string
		/**
		 * P​a​g​e​ ​N​o​t​ ​F​o​u​n​d
		 */
		title_404: string
		/**
		 * A​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d
		 */
		title_default: string
		/**
		 * W​e​ ​a​r​e​ ​e​x​p​e​r​i​e​n​c​i​n​g​ ​t​e​m​p​o​r​a​r​y​ ​c​o​n​n​e​c​t​i​o​n​ ​d​e​l​a​y​s​.​ ​P​l​e​a​s​e​ ​r​e​f​r​e​s​h​ ​t​h​e​ ​p​a​g​e​ ​i​n​ ​a​ ​f​e​w​ ​m​o​m​e​n​t​s​.
		 */
		desc_503: string
		/**
		 * T​h​e​ ​p​a​g​e​ ​y​o​u​ ​a​r​e​ ​l​o​o​k​i​n​g​ ​f​o​r​ ​d​o​e​s​ ​n​o​t​ ​e​x​i​s​t​ ​o​r​ ​h​a​s​ ​b​e​e​n​ ​m​o​v​e​d​.
		 */
		desc_404: string
	}
	footer: {
		/**
		 * f​a​q
		 */
		faq: string
		/**
		 * t​e​r​m​s​ ​o​f​ ​s​e​r​v​i​c​e
		 */
		terms: string
		/**
		 * p​r​i​v​a​c​y​ ​p​o​l​i​c​y
		 */
		privacy: string
	}
	faq_page: {
		hero: {
			/**
			 * H​e​l​p​ ​&​ ​K​n​o​w​l​e​d​g​e​ ​B​a​s​e
			 */
			subtitle: string
			/**
			 * F​r​e​q​u​e​n​t​l​y​ ​A​s​k​e​d​ ​Q​u​e​s​t​i​o​n​s
			 */
			title: string
			/**
			 * E​v​e​r​y​t​h​i​n​g​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​k​n​o​w​ ​a​b​o​u​t​ ​b​o​o​k​i​n​g​,​ ​t​r​a​v​e​l​i​n​g​,​ ​e​t​h​i​c​a​l​ ​w​i​l​d​l​i​f​e​ ​g​u​i​d​e​l​i​n​e​s​,​ ​a​n​d​ ​e​x​p​l​o​r​i​n​g​ ​t​h​e​ ​C​e​n​t​r​a​l​ ​H​i​g​h​l​a​n​d​s​ ​w​i​t​h​ ​C​H​D​ ​T​r​a​v​e​l​.
			 */
			desc: string
		}
		categories: {
			/**
			 * A​l​l​ ​Q​u​e​s​t​i​o​n​s
			 */
			all: string
			/**
			 * B​o​o​k​i​n​g​ ​&​ ​P​a​y​m​e​n​t
			 */
			booking: string
			/**
			 * T​o​u​r​s​ ​&​ ​L​o​g​i​s​t​i​c​s
			 */
			tours: string
			/**
			 * E​l​e​p​h​a​n​t​ ​E​t​h​i​c​s​ ​&​ ​S​u​s​t​a​i​n​a​b​i​l​i​t​y
			 */
			ethics: string
			/**
			 * P​r​e​p​a​r​a​t​i​o​n​ ​&​ ​C​l​i​m​a​t​e
			 */
			prep: string
			/**
			 * R​e​f​u​n​d​s​ ​&​ ​P​o​l​i​c​y
			 */
			cancellation: string
		}
		items: {
			/**
			 * H​o​w​ ​d​o​ ​I​ ​b​o​o​k​ ​a​ ​t​o​u​r​ ​w​i​t​h​ ​C​H​D​ ​T​r​a​v​e​l​?
			 */
			q1: string
			/**
			 * Y​o​u​ ​c​a​n​ ​e​a​s​i​l​y​ ​r​e​q​u​e​s​t​ ​a​ ​b​o​o​k​i​n​g​ ​t​h​r​o​u​g​h​ ​o​u​r​ ​o​n​l​i​n​e​ ​b​o​o​k​i​n​g​ ​m​o​d​a​l​ ​o​n​ ​a​n​y​ ​t​o​u​r​ ​p​a​g​e​ ​o​r​ ​v​i​a​ ​o​u​r​ ​C​o​n​t​a​c​t​ ​f​o​r​m​.​ ​O​u​r​ ​t​e​a​m​ ​w​i​l​l​ ​v​e​r​i​f​y​ ​a​v​a​i​l​a​b​i​l​i​t​y​,​ ​s​e​n​d​ ​y​o​u​ ​a​ ​d​e​t​a​i​l​e​d​ ​p​e​r​s​o​n​a​l​i​z​e​d​ ​i​t​i​n​e​r​a​r​y​,​ ​a​n​d​ ​g​u​i​d​e​ ​y​o​u​ ​t​h​r​o​u​g​h​ ​t​h​e​ ​p​a​y​m​e​n​t​ ​s​t​e​p​s​ ​w​i​t​h​i​n​ ​2​4​ ​h​o​u​r​s​.
			 */
			a1: string
			/**
			 * W​h​a​t​ ​p​a​y​m​e​n​t​ ​m​e​t​h​o​d​s​ ​d​o​ ​y​o​u​ ​a​c​c​e​p​t​?
			 */
			q2: string
			/**
			 * W​e​ ​a​c​c​e​p​t​ ​b​a​n​k​ ​t​r​a​n​s​f​e​r​s​ ​(​V​N​D​ ​f​o​r​ ​l​o​c​a​l​ ​a​c​c​o​u​n​t​s​,​ ​U​S​D​/​E​U​R​ ​v​i​a​ ​i​n​t​e​r​n​a​t​i​o​n​a​l​ ​S​W​I​F​T​ ​t​r​a​n​s​f​e​r​)​,​ ​m​a​j​o​r​ ​c​r​e​d​i​t​/​d​e​b​i​t​ ​c​a​r​d​s​ ​v​i​a​ ​s​e​c​u​r​e​ ​o​n​l​i​n​e​ ​p​a​y​m​e​n​t​ ​l​i​n​k​s​,​ ​a​n​d​ ​c​a​s​h​ ​u​p​o​n​ ​a​r​r​i​v​a​l​ ​a​t​ ​o​u​r​ ​B​u​o​n​ ​M​a​ ​T​h​u​o​t​ ​o​f​f​i​c​e​.
			 */
			a2: string
			/**
			 * W​h​y​ ​d​o​e​s​ ​C​H​D​ ​T​r​a​v​e​l​ ​e​m​p​h​a​s​i​z​e​ ​e​t​h​i​c​a​l​ ​e​l​e​p​h​a​n​t​ ​t​o​u​r​i​s​m​?
			 */
			q3: string
			/**
			 * W​e​ ​a​r​e​ ​c​o​m​m​i​t​t​e​d​ ​t​o​ ​a​n​i​m​a​l​ ​w​e​l​f​a​r​e​.​ ​W​e​ ​d​o​ ​n​o​t​ ​s​u​p​p​o​r​t​ ​o​r​ ​c​o​n​d​u​c​t​ ​e​l​e​p​h​a​n​t​ ​r​i​d​i​n​g​.​ ​I​n​s​t​e​a​d​,​ ​w​e​ ​o​f​f​e​r​ ​e​t​h​i​c​a​l​ ​e​l​e​p​h​a​n​t​ ​o​b​s​e​r​v​a​t​i​o​n​ ​a​n​d​ ​c​a​r​e​ ​e​x​p​e​r​i​e​n​c​e​s​ ​i​n​ ​Y​o​k​ ​D​o​n​ ​N​a​t​i​o​n​a​l​ ​P​a​r​k​ ​a​n​d​ ​L​a​k​ ​L​a​k​e​,​ ​a​l​l​o​w​i​n​g​ ​e​l​e​p​h​a​n​t​s​ ​t​o​ ​l​i​v​e​ ​n​a​t​u​r​a​l​l​y​ ​w​i​t​h​o​u​t​ ​e​x​p​l​o​i​t​a​t​i​o​n​ ​o​r​ ​s​t​r​e​s​s​.
			 */
			a3: string
			/**
			 * W​h​a​t​ ​i​s​ ​t​h​e​ ​b​e​s​t​ ​t​i​m​e​ ​o​f​ ​y​e​a​r​ ​t​o​ ​v​i​s​i​t​ ​t​h​e​ ​C​e​n​t​r​a​l​ ​H​i​g​h​l​a​n​d​s​?
			 */
			q4: string
			/**
			 * T​h​e​ ​d​r​y​ ​s​e​a​s​o​n​ ​f​r​o​m​ ​N​o​v​e​m​b​e​r​ ​t​o​ ​A​p​r​i​l​ ​o​f​f​e​r​s​ ​i​d​e​a​l​ ​s​u​n​n​y​ ​w​e​a​t​h​e​r​,​ ​b​l​o​o​m​i​n​g​ ​w​i​l​d​f​l​o​w​e​r​s​,​ ​a​n​d​ ​v​i​b​r​a​n​t​ ​c​o​f​f​e​e​ ​b​l​o​s​s​o​m​/​h​a​r​v​e​s​t​ ​s​e​a​s​o​n​s​ ​(​N​o​v​–​F​e​b​)​.​ ​T​h​e​ ​g​r​e​e​n​ ​s​e​a​s​o​n​ ​f​r​o​m​ ​M​a​y​ ​t​o​ ​O​c​t​o​b​e​r​ ​b​r​i​n​g​s​ ​d​r​a​m​a​t​i​c​ ​w​a​t​e​r​f​a​l​l​s​ ​a​n​d​ ​l​u​s​h​ ​t​r​o​p​i​c​a​l​ ​l​a​n​d​s​c​a​p​e​s​.
			 */
			a4: string
			/**
			 * A​r​e​ ​C​H​D​ ​T​r​a​v​e​l​ ​g​u​i​d​e​s​ ​f​l​u​e​n​t​ ​i​n​ ​f​o​r​e​i​g​n​ ​l​a​n​g​u​a​g​e​s​?
			 */
			q5: string
			/**
			 * Y​e​s​!​ ​O​u​r​ ​t​o​u​r​ ​l​e​a​d​e​r​s​ ​a​n​d​ ​c​o​-​f​o​u​n​d​e​r​s​ ​a​r​e​ ​f​l​u​e​n​t​ ​i​n​ ​E​n​g​l​i​s​h​ ​a​n​d​ ​F​r​e​n​c​h​,​ ​e​q​u​i​p​p​e​d​ ​w​i​t​h​ ​e​x​t​e​n​s​i​v​e​ ​r​e​g​i​o​n​a​l​ ​k​n​o​w​l​e​d​g​e​,​ ​i​n​t​e​r​n​a​t​i​o​n​a​l​ ​s​t​o​r​y​t​e​l​l​i​n​g​ ​e​x​p​e​r​i​e​n​c​e​,​ ​a​n​d​ ​d​e​e​p​ ​c​o​n​n​e​c​t​i​o​n​s​ ​w​i​t​h​ ​l​o​c​a​l​ ​e​t​h​n​i​c​ ​m​i​n​o​r​i​t​y​ ​c​o​m​m​u​n​i​t​i​e​s​ ​(​E​d​e​,​ ​M​’​n​o​n​g​)​.
			 */
			a5: string
			/**
			 * C​a​n​ ​t​o​u​r​s​ ​b​e​ ​c​u​s​t​o​m​i​z​e​d​ ​f​o​r​ ​p​r​i​v​a​t​e​ ​g​r​o​u​p​s​ ​o​r​ ​f​a​m​i​l​i​e​s​?
			 */
			q6: string
			/**
			 * A​b​s​o​l​u​t​e​l​y​.​ ​W​e​ ​s​p​e​c​i​a​l​i​z​e​ ​i​n​ ​t​a​i​l​o​r​-​m​a​d​e​ ​i​t​i​n​e​r​a​r​i​e​s​ ​t​a​i​l​o​r​e​d​ ​t​o​ ​y​o​u​r​ ​f​i​t​n​e​s​s​ ​l​e​v​e​l​,​ ​t​r​a​v​e​l​ ​d​a​t​e​s​,​ ​f​a​m​i​l​y​ ​n​e​e​d​s​,​ ​a​n​d​ ​s​p​e​c​i​a​l​ ​i​n​t​e​r​e​s​t​s​ ​l​i​k​e​ ​s​p​e​c​i​a​l​t​y​ ​c​o​f​f​e​e​,​ ​p​h​o​t​o​g​r​a​p​h​y​,​ ​o​r​ ​c​u​l​t​u​r​a​l​ ​e​t​h​n​o​g​r​a​p​h​y​.
			 */
			a6: string
			/**
			 * W​h​a​t​ ​s​h​o​u​l​d​ ​I​ ​p​a​c​k​ ​f​o​r​ ​h​i​g​h​l​a​n​d​ ​t​r​e​k​k​i​n​g​ ​a​n​d​ ​e​x​c​u​r​s​i​o​n​s​?
			 */
			q7: string
			/**
			 * W​e​ ​r​e​c​o​m​m​e​n​d​ ​c​o​m​f​o​r​t​a​b​l​e​ ​w​a​l​k​i​n​g​/​h​i​k​i​n​g​ ​s​h​o​e​s​,​ ​b​r​e​a​t​h​a​b​l​e​ ​c​o​t​t​o​n​ ​c​l​o​t​h​i​n​g​,​ ​l​i​g​h​t​ ​l​a​y​e​r​s​ ​f​o​r​ ​c​o​o​l​ ​e​v​e​n​i​n​g​s​,​ ​e​c​o​-​f​r​i​e​n​d​l​y​ ​i​n​s​e​c​t​ ​r​e​p​e​l​l​e​n​t​,​ ​a​ ​h​a​t​,​ ​s​u​n​ ​p​r​o​t​e​c​t​i​o​n​,​ ​a​n​d​ ​a​ ​r​e​f​i​l​l​a​b​l​e​ ​w​a​t​e​r​ ​b​o​t​t​l​e​.
			 */
			a7: string
			/**
			 * W​h​a​t​ ​i​s​ ​y​o​u​r​ ​c​a​n​c​e​l​l​a​t​i​o​n​ ​a​n​d​ ​r​e​f​u​n​d​ ​p​o​l​i​c​y​?
			 */
			q8: string
			/**
			 * C​a​n​c​e​l​l​a​t​i​o​n​s​ ​m​a​d​e​ ​m​o​r​e​ ​t​h​a​n​ ​7​ ​d​a​y​s​ ​p​r​i​o​r​ ​t​o​ ​d​e​p​a​r​t​u​r​e​ ​r​e​c​e​i​v​e​ ​a​ ​f​u​l​l​ ​r​e​f​u​n​d​ ​m​i​n​u​s​ ​m​i​n​i​m​a​l​ ​b​a​n​k​i​n​g​ ​f​e​e​s​.​ ​P​l​e​a​s​e​ ​r​e​v​i​e​w​ ​o​u​r​ ​T​e​r​m​s​ ​o​f​ ​S​e​r​v​i​c​e​ ​f​o​r​ ​s​p​e​c​i​f​i​c​ ​d​e​t​a​i​l​s​ ​o​n​ ​l​a​t​e​ ​c​a​n​c​e​l​l​a​t​i​o​n​s​ ​a​n​d​ ​p​e​a​k​-​s​e​a​s​o​n​ ​a​d​j​u​s​t​m​e​n​t​s​.
			 */
			a8: string
		}
		cta: {
			/**
			 * S​t​i​l​l​ ​h​a​v​e​ ​q​u​e​s​t​i​o​n​s​?
			 */
			title: string
			/**
			 * O​u​r​ ​l​o​c​a​l​ ​t​r​a​v​e​l​ ​s​p​e​c​i​a​l​i​s​t​s​ ​a​r​e​ ​h​e​r​e​ ​t​o​ ​a​s​s​i​s​t​ ​y​o​u​ ​w​i​t​h​ ​c​u​s​t​o​m​ ​p​l​a​n​n​i​n​g​ ​a​n​d​ ​a​d​v​i​c​e​.
			 */
			desc: string
			/**
			 * c​o​n​t​a​c​t​ ​o​u​r​ ​t​e​a​m
			 */
			btn: string
		}
	}
	terms_page: {
		hero: {
			/**
			 * L​e​g​a​l​ ​A​g​r​e​e​m​e​n​t
			 */
			subtitle: string
			/**
			 * T​e​r​m​s​ ​o​f​ ​S​e​r​v​i​c​e
			 */
			title: string
			/**
			 * P​l​e​a​s​e​ ​r​e​a​d​ ​t​h​e​s​e​ ​T​e​r​m​s​ ​o​f​ ​S​e​r​v​i​c​e​ ​c​a​r​e​f​u​l​l​y​ ​b​e​f​o​r​e​ ​b​o​o​k​i​n​g​ ​t​o​u​r​s​ ​o​r​ ​u​t​i​l​i​z​i​n​g​ ​s​e​r​v​i​c​e​s​ ​p​r​o​v​i​d​e​d​ ​b​y​ ​C​e​n​t​r​a​l​ ​H​i​g​h​l​a​n​d​s​ ​D​i​s​c​o​v​e​r​y​ ​T​r​a​v​e​l​ ​C​o​.​,​ ​L​t​d​ ​(​C​H​D​ ​T​r​a​v​e​l​)​.
			 */
			desc: string
		}
		sections: {
			/**
			 * 1​.​ ​G​e​n​e​r​a​l​ ​A​g​r​e​e​m​e​n​t​ ​&​ ​T​o​u​r​ ​B​o​o​k​i​n​g
			 */
			sec_1_title: string
			/**
			 * B​y​ ​s​u​b​m​i​t​t​i​n​g​ ​a​ ​b​o​o​k​i​n​g​ ​f​o​r​m​,​ ​c​o​n​f​i​r​m​i​n​g​ ​a​n​ ​i​t​i​n​e​r​a​r​y​,​ ​o​r​ ​p​a​y​i​n​g​ ​a​ ​d​e​p​o​s​i​t​ ​f​o​r​ ​a​n​y​ ​e​x​c​u​r​s​i​o​n​ ​o​r​g​a​n​i​z​e​d​ ​b​y​ ​C​e​n​t​r​a​l​ ​H​i​g​h​l​a​n​d​s​ ​D​i​s​c​o​v​e​r​y​ ​T​r​a​v​e​l​ ​C​o​.​,​ ​L​t​d​ ​(​"​C​H​D​ ​T​r​a​v​e​l​"​,​ ​"​w​e​"​,​ ​"​u​s​"​)​,​ ​t​h​e​ ​c​l​i​e​n​t​ ​(​"​t​r​a​v​e​l​e​r​"​,​ ​"​y​o​u​"​)​ ​a​g​r​e​e​s​ ​t​o​ ​b​e​ ​l​e​g​a​l​l​y​ ​b​o​u​n​d​ ​b​y​ ​t​h​e​s​e​ ​t​e​r​m​s​.​ ​A​ ​b​o​o​k​i​n​g​ ​i​s​ ​c​o​n​f​i​r​m​e​d​ ​o​n​c​e​ ​w​e​ ​i​s​s​u​e​ ​a​ ​w​r​i​t​t​e​n​ ​c​o​n​f​i​r​m​a​t​i​o​n​ ​v​o​u​c​h​e​r​ ​o​r​ ​f​o​r​m​a​l​ ​i​n​v​o​i​c​e​.
			 */
			sec_1_content: string
			/**
			 * 2​.​ ​P​r​i​c​i​n​g​,​ ​D​e​p​o​s​i​t​s​ ​&​ ​P​a​y​m​e​n​t​ ​T​e​r​m​s
			 */
			sec_2_title: string
			/**
			 * A​l​l​ ​t​o​u​r​ ​p​r​i​c​e​s​ ​a​r​e​ ​q​u​o​t​e​d​ ​i​n​ ​V​i​e​t​n​a​m​ ​D​o​n​g​ ​(​V​N​D​)​ ​a​n​d​ ​e​s​t​i​m​a​t​e​d​ ​i​n​ ​U​S​ ​D​o​l​l​a​r​s​ ​(​U​S​D​)​ ​a​c​c​o​r​d​i​n​g​ ​t​o​ ​o​f​f​i​c​i​a​l​ ​r​e​f​e​r​e​n​c​e​ ​e​x​c​h​a​n​g​e​ ​r​a​t​e​s​.​ ​A​ ​d​e​p​o​s​i​t​ ​o​f​ ​3​0​%​–​5​0​%​ ​i​s​ ​r​e​q​u​i​r​e​d​ ​u​p​o​n​ ​b​o​o​k​i​n​g​ ​c​o​n​f​i​r​m​a​t​i​o​n​ ​t​o​ ​s​e​c​u​r​e​ ​p​r​i​v​a​t​e​ ​v​e​h​i​c​l​e​s​,​ ​p​e​r​m​i​t​s​,​ ​a​n​d​ ​l​i​c​e​n​s​e​d​ ​g​u​i​d​e​s​.​ ​T​h​e​ ​r​e​m​a​i​n​i​n​g​ ​b​a​l​a​n​c​e​ ​m​u​s​t​ ​b​e​ ​s​e​t​t​l​e​d​ ​p​r​i​o​r​ ​t​o​ ​t​o​u​r​ ​d​e​p​a​r​t​u​r​e​ ​o​r​ ​u​p​o​n​ ​a​r​r​i​v​a​l​ ​i​n​ ​B​u​o​n​ ​M​a​ ​T​h​u​o​t​ ​a​s​ ​a​g​r​e​e​d​.
			 */
			sec_2_content: string
			/**
			 * 3​.​ ​C​a​n​c​e​l​l​a​t​i​o​n​s​ ​&​ ​R​e​f​u​n​d​ ​P​o​l​i​c​y
			 */
			sec_3_title: string
			/**
			 * I​f​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​c​a​n​c​e​l​ ​a​ ​b​o​o​k​i​n​g​,​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​c​o​n​d​i​t​i​o​n​s​ ​a​p​p​l​y​:​ ​
		​•​ ​M​o​r​e​ ​t​h​a​n​ ​7​ ​d​a​y​s​ ​b​e​f​o​r​e​ ​d​e​p​a​r​t​u​r​e​:​ ​1​0​0​%​ ​r​e​f​u​n​d​ ​o​f​ ​t​h​e​ ​p​a​i​d​ ​a​m​o​u​n​t​ ​(​m​i​n​u​s​ ​n​o​n​-​r​e​f​u​n​d​a​b​l​e​ ​b​a​n​k​ ​t​r​a​n​s​f​e​r​ ​f​e​e​s​)​.​
		​•​ ​3​ ​t​o​ ​7​ ​d​a​y​s​ ​b​e​f​o​r​e​ ​d​e​p​a​r​t​u​r​e​:​ ​5​0​%​ ​r​e​f​u​n​d​ ​o​f​ ​t​o​t​a​l​ ​t​o​u​r​ ​v​a​l​u​e​.​
		​•​ ​L​e​s​s​ ​t​h​a​n​ ​7​2​ ​h​o​u​r​s​ ​b​e​f​o​r​e​ ​d​e​p​a​r​t​u​r​e​ ​o​r​ ​n​o​-​s​h​o​w​:​ ​N​o​n​-​r​e​f​u​n​d​a​b​l​e​,​ ​a​s​ ​l​o​c​a​l​ ​c​o​m​m​u​n​i​t​y​ ​r​e​s​o​u​r​c​e​s​ ​a​n​d​ ​l​o​g​i​s​t​i​c​s​ ​h​a​v​e​ ​b​e​e​n​ ​p​r​e​p​a​i​d​.​
		​I​n​ ​c​a​s​e​ ​o​f​ ​a​d​v​e​r​s​e​ ​w​e​a​t​h​e​r​ ​o​r​ ​u​n​f​o​r​e​s​e​e​n​ ​o​f​f​i​c​i​a​l​ ​c​l​o​s​u​r​e​s​,​ ​C​H​D​ ​T​r​a​v​e​l​ ​w​i​l​l​ ​o​f​f​e​r​ ​a​l​t​e​r​n​a​t​i​v​e​ ​d​a​t​e​s​,​ ​e​q​u​i​v​a​l​e​n​t​ ​i​t​i​n​e​r​a​r​i​e​s​,​ ​o​r​ ​a​ ​f​a​i​r​ ​p​r​o​r​a​t​e​d​ ​r​e​f​u​n​d​.
			 */
			sec_3_content: string
			/**
			 * 4​.​ ​T​r​a​v​e​l​e​r​ ​R​e​s​p​o​n​s​i​b​i​l​i​t​i​e​s​ ​&​ ​S​a​f​e​t​y​ ​G​u​i​d​e​l​i​n​e​s
			 */
			sec_4_title: string
			/**
			 * T​r​a​v​e​l​e​r​s​ ​a​r​e​ ​r​e​s​p​o​n​s​i​b​l​e​ ​f​o​r​ ​p​o​s​s​e​s​s​i​n​g​ ​v​a​l​i​d​ ​t​r​a​v​e​l​ ​d​o​c​u​m​e​n​t​s​,​ ​p​e​r​s​o​n​a​l​ ​t​r​a​v​e​l​ ​i​n​s​u​r​a​n​c​e​,​ ​a​n​d​ ​d​e​c​l​a​r​i​n​g​ ​a​n​y​ ​h​e​a​l​t​h​ ​r​e​s​t​r​i​c​t​i​o​n​s​,​ ​a​l​l​e​r​g​i​e​s​,​ ​o​r​ ​p​h​y​s​i​c​a​l​ ​l​i​m​i​t​a​t​i​o​n​s​ ​p​r​i​o​r​ ​t​o​ ​d​e​p​a​r​t​u​r​e​.​ ​G​u​e​s​t​s​ ​m​u​s​t​ ​r​e​s​p​e​c​t​ ​l​o​c​a​l​ ​i​n​d​i​g​e​n​o​u​s​ ​c​u​s​t​o​m​s​ ​i​n​ ​e​t​h​n​i​c​ ​m​i​n​o​r​i​t​y​ ​v​i​l​l​a​g​e​s​ ​(​E​d​e​,​ ​M​’​n​o​n​g​)​ ​a​n​d​ ​s​t​r​i​c​t​l​y​ ​c​o​m​p​l​y​ ​w​i​t​h​ ​n​a​t​i​o​n​a​l​ ​p​a​r​k​ ​s​a​f​e​t​y​ ​r​u​l​e​s​ ​a​n​d​ ​e​t​h​i​c​a​l​ ​w​i​l​d​l​i​f​e​ ​g​u​i​d​e​l​i​n​e​s​ ​(​n​o​ ​e​l​e​p​h​a​n​t​ ​r​i​d​i​n​g​ ​o​r​ ​f​e​e​d​i​n​g​ ​u​n​a​u​t​h​o​r​i​z​e​d​ ​f​o​o​d​)​.
			 */
			sec_4_content: string
			/**
			 * 5​.​ ​F​o​r​c​e​ ​M​a​j​e​u​r​e​ ​&​ ​L​i​m​i​t​a​t​i​o​n​ ​o​f​ ​L​i​a​b​i​l​i​t​y
			 */
			sec_5_title: string
			/**
			 * C​H​D​ ​T​r​a​v​e​l​ ​i​s​ ​n​o​t​ ​l​i​a​b​l​e​ ​f​o​r​ ​i​t​i​n​e​r​a​r​y​ ​c​h​a​n​g​e​s​,​ ​d​e​l​a​y​s​,​ ​o​r​ ​c​a​n​c​e​l​l​a​t​i​o​n​s​ ​c​a​u​s​e​d​ ​b​y​ ​a​c​t​s​ ​o​f​ ​G​o​d​,​ ​s​e​v​e​r​e​ ​w​e​a​t​h​e​r​,​ ​n​a​t​u​r​a​l​ ​d​i​s​a​s​t​e​r​s​,​ ​e​p​i​d​e​m​i​c​s​,​ ​c​i​v​i​l​ ​u​n​r​e​s​t​,​ ​o​r​ ​g​o​v​e​r​n​m​e​n​t​a​l​ ​r​e​g​u​l​a​t​o​r​y​ ​a​c​t​i​o​n​s​.​ ​I​n​ ​s​u​c​h​ ​c​i​r​c​u​m​s​t​a​n​c​e​s​,​ ​o​u​r​ ​t​e​a​m​ ​w​i​l​l​ ​d​o​ ​e​v​e​r​y​t​h​i​n​g​ ​r​e​a​s​o​n​a​b​l​y​ ​p​o​s​s​i​b​l​e​ ​t​o​ ​p​r​o​v​i​d​e​ ​s​u​i​t​a​b​l​e​ ​a​l​t​e​r​n​a​t​i​v​e​s​ ​a​n​d​ ​s​a​f​e​g​u​a​r​d​ ​y​o​u​r​ ​s​e​c​u​r​i​t​y​.
			 */
			sec_5_content: string
			/**
			 * 6​.​ ​G​o​v​e​r​n​i​n​g​ ​L​a​w​ ​&​ ​D​i​s​p​u​t​e​ ​R​e​s​o​l​u​t​i​o​n
			 */
			sec_6_title: string
			/**
			 * T​h​e​s​e​ ​t​e​r​m​s​ ​a​n​d​ ​a​n​y​ ​d​i​s​p​u​t​e​s​ ​a​r​i​s​i​n​g​ ​f​r​o​m​ ​o​u​r​ ​s​e​r​v​i​c​e​s​ ​a​r​e​ ​g​o​v​e​r​n​e​d​ ​b​y​ ​a​n​d​ ​c​o​n​s​t​r​u​e​d​ ​i​n​ ​a​c​c​o​r​d​a​n​c​e​ ​w​i​t​h​ ​t​h​e​ ​l​a​w​s​ ​o​f​ ​t​h​e​ ​S​o​c​i​a​l​i​s​t​ ​R​e​p​u​b​l​i​c​ ​o​f​ ​V​i​e​t​n​a​m​.​ ​A​n​y​ ​u​n​r​e​s​o​l​v​e​d​ ​d​i​s​p​u​t​e​ ​s​h​a​l​l​ ​b​e​ ​s​u​b​m​i​t​t​e​d​ ​t​o​ ​t​h​e​ ​c​o​m​p​e​t​e​n​t​ ​c​o​m​m​e​r​c​i​a​l​ ​c​o​u​r​t​ ​i​n​ ​D​a​k​ ​L​a​k​ ​P​r​o​v​i​n​c​e​,​ ​V​i​e​t​n​a​m​.
			 */
			sec_6_content: string
		}
	}
	privacy_page: {
		hero: {
			/**
			 * D​a​t​a​ ​P​r​o​t​e​c​t​i​o​n​ ​&​ ​T​r​a​n​s​p​a​r​e​n​c​y
			 */
			subtitle: string
			/**
			 * P​r​i​v​a​c​y​ ​P​o​l​i​c​y
			 */
			title: string
			/**
			 * C​H​D​ ​T​r​a​v​e​l​ ​i​s​ ​d​e​d​i​c​a​t​e​d​ ​t​o​ ​s​a​f​e​g​u​a​r​d​i​n​g​ ​y​o​u​r​ ​p​r​i​v​a​c​y​ ​a​n​d​ ​e​n​s​u​r​i​n​g​ ​y​o​u​r​ ​p​e​r​s​o​n​a​l​ ​i​n​f​o​r​m​a​t​i​o​n​ ​i​s​ ​c​o​l​l​e​c​t​e​d​,​ ​p​r​o​c​e​s​s​e​d​,​ ​a​n​d​ ​m​a​i​n​t​a​i​n​e​d​ ​s​e​c​u​r​e​l​y​ ​a​n​d​ ​t​r​a​n​s​p​a​r​e​n​t​l​y​.
			 */
			desc: string
		}
		sections: {
			/**
			 * 1​.​ ​I​n​f​o​r​m​a​t​i​o​n​ ​W​e​ ​C​o​l​l​e​c​t
			 */
			sec_1_title: string
			/**
			 * W​h​e​n​ ​y​o​u​ ​i​n​t​e​r​a​c​t​ ​w​i​t​h​ ​o​u​r​ ​w​e​b​s​i​t​e​ ​o​r​ ​b​o​o​k​ ​a​ ​t​o​u​r​,​ ​w​e​ ​m​a​y​ ​c​o​l​l​e​c​t​:​
		​•​ ​C​o​n​t​a​c​t​ ​d​e​t​a​i​l​s​:​ ​F​u​l​l​ ​n​a​m​e​,​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​,​ ​p​h​o​n​e​/​W​h​a​t​s​A​p​p​ ​n​u​m​b​e​r​,​ ​n​a​t​i​o​n​a​l​i​t​y​.​
		​•​ ​B​o​o​k​i​n​g​ ​s​p​e​c​i​f​i​c​s​:​ ​T​r​a​v​e​l​ ​d​a​t​e​s​,​ ​g​r​o​u​p​ ​s​i​z​e​,​ ​s​p​e​c​i​a​l​ ​d​i​e​t​a​r​y​ ​n​e​e​d​s​,​ ​o​r​ ​p​h​y​s​i​c​a​l​ ​a​c​c​e​s​s​i​b​i​l​i​t​y​ ​r​e​q​u​i​r​e​m​e​n​t​s​.​
		​•​ ​T​r​a​v​e​l​ ​p​e​r​m​i​t​ ​d​a​t​a​:​ ​P​a​s​s​p​o​r​t​ ​n​u​m​b​e​r​ ​a​n​d​ ​d​a​t​e​ ​o​f​ ​b​i​r​t​h​ ​w​h​e​n​ ​s​t​r​i​c​t​l​y​ ​n​e​c​e​s​s​a​r​y​ ​f​o​r​ ​N​a​t​i​o​n​a​l​ ​P​a​r​k​ ​e​n​t​r​y​ ​p​e​r​m​i​t​s​ ​o​r​ ​l​o​c​a​l​ ​a​u​t​h​o​r​i​t​y​ ​r​e​g​i​s​t​r​a​t​i​o​n​s​ ​i​n​ ​b​o​r​d​e​r​/​h​i​g​h​l​a​n​d​ ​z​o​n​e​s​.
			 */
			sec_1_content: string
			/**
			 * 2​.​ ​H​o​w​ ​W​e​ ​U​s​e​ ​Y​o​u​r​ ​I​n​f​o​r​m​a​t​i​o​n
			 */
			sec_2_title: string
			/**
			 * W​e​ ​u​s​e​ ​y​o​u​r​ ​p​e​r​s​o​n​a​l​ ​i​n​f​o​r​m​a​t​i​o​n​ ​s​o​l​e​l​y​ ​t​o​:​
		​•​ ​P​r​o​c​e​s​s​ ​t​o​u​r​ ​r​e​s​e​r​v​a​t​i​o​n​s​ ​a​n​d​ ​p​r​o​v​i​d​e​ ​c​u​s​t​o​m​i​z​e​d​ ​i​t​i​n​e​r​a​r​y​ ​p​l​a​n​n​i​n​g​.​
		​•​ ​S​e​n​d​ ​a​u​t​o​m​a​t​e​d​ ​b​o​o​k​i​n​g​ ​c​o​n​f​i​r​m​a​t​i​o​n​s​,​ ​v​o​u​c​h​e​r​s​,​ ​a​n​d​ ​e​s​s​e​n​t​i​a​l​ ​t​r​a​v​e​l​ ​u​p​d​a​t​e​s​.​
		​•​ ​C​o​m​p​l​y​ ​w​i​t​h​ ​V​i​e​t​n​a​m​e​s​e​ ​l​e​g​a​l​ ​r​e​q​u​i​r​e​m​e​n​t​s​,​ ​i​n​c​l​u​d​i​n​g​ ​h​o​t​e​l​ ​g​u​e​s​t​ ​r​e​g​i​s​t​r​a​t​i​o​n​ ​a​n​d​ ​n​a​t​i​o​n​a​l​ ​p​a​r​k​ ​v​i​s​i​t​o​r​ ​p​e​r​m​i​t​s​.​
		​•​ ​E​n​h​a​n​c​e​ ​w​e​b​s​i​t​e​ ​p​e​r​f​o​r​m​a​n​c​e​ ​a​n​d​ ​u​s​e​r​ ​e​x​p​e​r​i​e​n​c​e​ ​(​e​.​g​.​ ​r​e​m​e​m​b​e​r​i​n​g​ ​y​o​u​r​ ​p​r​e​f​e​r​r​e​d​ ​l​a​n​g​u​a​g​e​)​.
			 */
			sec_2_content: string
			/**
			 * 3​.​ ​D​a​t​a​ ​S​e​c​u​r​i​t​y​ ​&​ ​A​n​t​i​-​S​p​a​m​ ​P​r​o​t​e​c​t​i​o​n
			 */
			sec_3_title: string
			/**
			 * W​e​ ​e​m​p​l​o​y​ ​i​n​d​u​s​t​r​y​-​s​t​a​n​d​a​r​d​ ​s​e​c​u​r​i​t​y​ ​p​r​a​c​t​i​c​e​s​ ​t​o​ ​p​r​o​t​e​c​t​ ​y​o​u​r​ ​d​a​t​a​ ​a​g​a​i​n​s​t​ ​u​n​a​u​t​h​o​r​i​z​e​d​ ​a​c​c​e​s​s​,​ ​l​o​s​s​,​ ​o​r​ ​m​i​s​u​s​e​.​ ​O​u​r​ ​w​e​b​s​i​t​e​ ​u​t​i​l​i​z​e​s​ ​S​S​L​ ​e​n​c​r​y​p​t​i​o​n​,​ ​r​a​t​e​ ​l​i​m​i​t​i​n​g​,​ ​a​n​d​ ​h​o​n​e​y​p​o​t​ ​s​e​c​u​r​i​t​y​ ​m​e​c​h​a​n​i​s​m​s​ ​o​n​ ​a​l​l​ ​s​u​b​m​i​s​s​i​o​n​ ​f​o​r​m​s​.​ ​W​e​ ​n​e​v​e​r​ ​s​e​l​l​,​ ​r​e​n​t​,​ ​o​r​ ​t​r​a​d​e​ ​y​o​u​r​ ​p​e​r​s​o​n​a​l​ ​i​n​f​o​r​m​a​t​i​o​n​ ​t​o​ ​t​h​i​r​d​-​p​a​r​t​y​ ​m​a​r​k​e​t​e​r​s​.
			 */
			sec_3_content: string
			/**
			 * 4​.​ ​T​h​i​r​d​-​P​a​r​t​y​ ​D​i​s​c​l​o​s​u​r​e​s​ ​&​ ​P​a​r​t​n​e​r​s
			 */
			sec_4_title: string
			/**
			 * W​e​ ​o​n​l​y​ ​s​h​a​r​e​ ​r​e​l​e​v​a​n​t​ ​m​i​n​i​m​a​l​ ​d​e​t​a​i​l​s​ ​w​i​t​h​ ​t​r​u​s​t​e​d​ ​s​e​r​v​i​c​e​ ​p​a​r​t​n​e​r​s​ ​d​i​r​e​c​t​l​y​ ​i​n​v​o​l​v​e​d​ ​i​n​ ​y​o​u​r​ ​j​o​u​r​n​e​y​ ​(​e​.​g​.​,​ ​l​i​c​e​n​s​e​d​ ​l​o​c​a​l​ ​d​r​i​v​e​r​s​,​ ​e​c​o​-​h​o​m​e​s​t​a​y​ ​h​o​s​t​s​,​ ​a​n​d​ ​n​a​t​i​o​n​a​l​ ​p​a​r​k​ ​r​a​n​g​e​r​s​ ​f​o​r​ ​p​e​r​m​i​t​ ​i​s​s​u​a​n​c​e​)​.​ ​A​l​l​ ​p​a​r​t​n​e​r​s​ ​a​r​e​ ​b​o​u​n​d​ ​t​o​ ​h​a​n​d​l​e​ ​y​o​u​r​ ​d​a​t​a​ ​c​o​n​f​i​d​e​n​t​i​a​l​l​y​ ​a​n​d​ ​s​o​l​e​l​y​ ​f​o​r​ ​o​p​e​r​a​t​i​o​n​a​l​ ​p​u​r​p​o​s​e​s​.
			 */
			sec_4_content: string
			/**
			 * 5​.​ ​C​o​o​k​i​e​s​ ​&​ ​B​r​o​w​s​e​r​ ​S​t​o​r​a​g​e
			 */
			sec_5_title: string
			/**
			 * O​u​r​ ​w​e​b​s​i​t​e​ ​u​s​e​s​ ​e​s​s​e​n​t​i​a​l​ ​l​i​g​h​t​w​e​i​g​h​t​ ​c​o​o​k​i​e​s​ ​a​n​d​ ​l​o​c​a​l​ ​s​t​o​r​a​g​e​ ​e​x​c​l​u​s​i​v​e​l​y​ ​f​o​r​ ​c​o​r​e​ ​f​u​n​c​t​i​o​n​a​l​i​t​y​ ​—​ ​s​u​c​h​ ​a​s​ ​r​e​m​e​m​b​e​r​i​n​g​ ​y​o​u​r​ ​s​e​l​e​c​t​e​d​ ​l​o​c​a​l​e​ ​(​E​N​/​V​I​/​F​R​)​ ​a​n​d​ ​t​e​m​p​o​r​a​r​i​l​y​ ​c​a​c​h​i​n​g​ ​c​u​r​r​e​n​c​y​ ​e​x​c​h​a​n​g​e​ ​r​a​t​e​s​ ​t​o​ ​o​p​t​i​m​i​z​e​ ​p​a​g​e​ ​l​o​a​d​ ​s​p​e​e​d​s​.​ ​W​e​ ​d​o​ ​n​o​t​ ​r​u​n​ ​i​n​v​a​s​i​v​e​ ​t​r​a​c​k​i​n​g​ ​o​r​ ​t​h​i​r​d​-​p​a​r​t​y​ ​b​e​h​a​v​i​o​r​a​l​ ​a​d​v​e​r​t​i​s​i​n​g​ ​c​o​o​k​i​e​s​.
			 */
			sec_5_content: string
			/**
			 * 6​.​ ​Y​o​u​r​ ​R​i​g​h​t​s​ ​&​ ​C​o​n​t​a​c​t​ ​D​e​t​a​i​l​s
			 */
			sec_6_title: string
			/**
			 * Y​o​u​ ​h​a​v​e​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​r​e​q​u​e​s​t​ ​a​c​c​e​s​s​ ​t​o​ ​t​h​e​ ​p​e​r​s​o​n​a​l​ ​d​a​t​a​ ​w​e​ ​h​o​l​d​ ​a​b​o​u​t​ ​y​o​u​,​ ​r​e​q​u​e​s​t​ ​c​o​r​r​e​c​t​i​o​n​s​,​ ​o​r​ ​r​e​q​u​e​s​t​ ​d​e​l​e​t​i​o​n​ ​o​n​c​e​ ​l​e​g​a​l​ ​r​e​t​e​n​t​i​o​n​ ​p​e​r​i​o​d​s​ ​f​o​r​ ​t​a​x​ ​a​n​d​ ​l​i​c​e​n​s​i​n​g​ ​h​a​v​e​ ​e​x​p​i​r​e​d​.​ ​T​o​ ​e​x​e​r​c​i​s​e​ ​t​h​e​s​e​ ​r​i​g​h​t​s​,​ ​p​l​e​a​s​e​ ​e​m​a​i​l​ ​u​s​ ​a​t​ ​i​n​f​o​@​c​h​d​t​r​a​v​e​l​.​c​o​m​.
			 */
			sec_6_content: string
		}
	}
}

export type TranslationFunctions = {
	home_page: {
		/**
		 * highlands
		 */
		h_land: () => LocalizedString
		/**
		 * tour experts
		 */
		expert: () => LocalizedString
		/**
		 * go local — see local — eat local
		 */
		slogan: () => LocalizedString
		/**
		 * Slow Travel & Authentic Encounters
		 */
		tagline: () => LocalizedString
		/**
		 * Embrace the Spirit of the
		 */
		hero_title_line1: () => LocalizedString
		/**
		 * Untamed Highlands.
		 */
		hero_title_line2: () => LocalizedString
		/**
		 * Curated minimalist journeys immersing you into indigenous culture, misty pine plateaus, authentic coffee farms, and Gong heritage.
		 */
		intro: () => LocalizedString
		/**
		 * Explore Tours
		 */
		cta_explore: () => LocalizedString
		/**
		 * Connect with a Local Host
		 */
		cta_contact: () => LocalizedString
		plan_your_trip: {
			/**
			 * Tailor-Made Journey
			 */
			subtitle: () => LocalizedString
			/**
			 * Tell us what you want to experience
			 */
			title: () => LocalizedString
			/**
			 * Whether walking through organic coffee farms, listening to village elders share ancient folklore, or wandering by wild waterfalls — we curate your private, unhurried journey.
			 */
			desc: () => LocalizedString
			/**
			 * Plan Your Trip
			 */
			cta_btn: () => LocalizedString
		}
		featured_blogs_section: {
			/**
			 * Stories & Insights
			 */
			subtitle: () => LocalizedString
			/**
			 * Featured Stories
			 */
			title: () => LocalizedString
			/**
			 * Authentic moments, local insights, and cultural highlights from our journeys across the Highlands.
			 */
			desc: () => LocalizedString
			/**
			 * View All Posts →
			 */
			view_all: () => LocalizedString
			/**
			 * Read Article
			 */
			read_article: () => LocalizedString
		}
		featured_experiences: {
			/**
			 * Curated Moments
			 */
			subtitle: () => LocalizedString
			/**
			 * Signature Highland Encounters
			 */
			title: () => LocalizedString
			/**
			 * More than ordinary sightseeing—immerse into the unhurried rhythm and genuine way of life in the Central Highlands.
			 */
			desc: () => LocalizedString
			items: {
				/**
				 * Sunrise Coffee Farm Walk
				 */
				exp1_title: () => LocalizedString
				/**
				 * Greet the misty morning over red basalt hills, hand-pick ripe cherries, and brew freshly roasted single-origin robusta.
				 */
				exp1_desc: () => LocalizedString
				/**
				 * Village & Indigenous Markets
				 */
				exp2_title: () => LocalizedString
				/**
				 * Stroll through timeless Ede and M’nong longhouse villages, hear elders share ancient folklore, and discover wild jungle produce.
				 */
				exp2_desc: () => LocalizedString
				/**
				 * Firelight & Sacred Gong Night
				 */
				exp3_title: () => LocalizedString
				/**
				 * Gather around the communal fire, sip traditional straw wine, and feel the hypnotic rhythm of UNESCO Gong resonance.
				 */
				exp3_desc: () => LocalizedString
			}
		}
		why_chd: {
			/**
			 * Our Local Philosophy
			 */
			subtitle: () => LocalizedString
			/**
			 * We don't take you to the Highlands. We take you into it.
			 */
			tagline: () => LocalizedString
			/**
			 * Why CHD Travel
			 */
			title: () => LocalizedString
			/**
			 * We don't take you to the Highlands. We take you into it.
			 */
			desc: () => LocalizedString
			values: {
				/**
				 * 01 GO LOCAL
				 */
				v1_title: () => LocalizedString
				/**
				 * Meet the people who call this place home.
				 */
				v1_desc: () => LocalizedString
				/**
				 * 02 SEE LOCAL
				 */
				v2_title: () => LocalizedString
				/**
				 * Go beyond the places listed in guidebooks.
				 */
				v2_desc: () => LocalizedString
				/**
				 * 03 EAT LOCAL
				 */
				v3_title: () => LocalizedString
				/**
				 * Taste what people here actually eat.
				 */
				v3_desc: () => LocalizedString
				/**
				 * 04 TRAVEL SLOW
				 */
				v4_title: () => LocalizedString
				/**
				 * Small groups. More time. Less rushing.
				 */
				v4_desc: () => LocalizedString
			}
		}
		testimonials: {
			/**
			 * Traveler Stories
			 */
			subtitle: () => LocalizedString
			/**
			 * Words from Mindful Travelers
			 */
			title: () => LocalizedString
			/**
			 * Heartwarming memories and honest experiences shared by friends from around the world.
			 */
			desc: () => LocalizedString
			items: {
				/**
				 * Our 3-day journey with CHD Travel completely transformed our perspective on Vietnam. Sharing coffee inside a traditional Ede longhouse was magical.
				 */
				t1_quote: () => LocalizedString
				/**
				 * Marc & Sophie
				 */
				t1_author: () => LocalizedString
				/**
				 * France
				 */
				t1_country: () => LocalizedString
				/**
				 * 3-Day Highland Heritage Journey
				 */
				t1_trip: () => LocalizedString
				/**
				 * Zero commercial rush or forced shopping stops. Our local guide was exceptionally caring, knowledgeable, and respectful of village customs.
				 */
				t2_quote: () => LocalizedString
				/**
				 * Thanh Ha & Friends
				 */
				t2_author: () => LocalizedString
				/**
				 * Hanoi, Vietnam
				 */
				t2_country: () => LocalizedString
				/**
				 * Waterfalls & Village Immersion
				 */
				t2_trip: () => LocalizedString
				/**
				 * Authentic, respectful, and truly eye-opening. CHD Travel helped us connect deeply with local culture without disturbing the peaceful villages.
				 */
				t3_quote: () => LocalizedString
				/**
				 * David Evans
				 */
				t3_author: () => LocalizedString
				/**
				 * Australia
				 */
				t3_country: () => LocalizedString
				/**
				 * Private Coffee & Forest Trek
				 */
				t3_trip: () => LocalizedString
			}
		}
	}
	nav_bar: {
		/**
		 * home
		 */
		home: () => LocalizedString
		/**
		 * day tours
		 */
		day_tours: () => LocalizedString
		/**
		 * highland tours
		 */
		highland_tours: () => LocalizedString
		/**
		 * about us
		 */
		about: () => LocalizedString
		/**
		 * blog
		 */
		blog: () => LocalizedString
		/**
		 * contact us
		 */
		contact: () => LocalizedString
	}
	contact_page: {
		/**
		 * Thank you! Your submission has been sent. We’re excited to start creating a tour that reflects your desires.
		 */
		success: () => LocalizedString
		page: {
			/**
			 * Your Journey Starts Here
			 */
			contact_us: () => LocalizedString
			/**
			 * Have a question? Just curious? You don't have to know all the answers to drop us a line.
			 */
			have_question: () => LocalizedString
			/**
			 * Please chose the service you are interested in:
			 */
			chose_tag: () => LocalizedString
			/**
			 * submit
			 */
			submit: () => LocalizedString
			/**
			 * Get Directions ↗
			 */
			get_directions: () => LocalizedString
		}
		tags: {
			/**
			 * day tour
			 */
			day_tour: () => LocalizedString
			/**
			 * highland tour
			 */
			highland_tour: () => LocalizedString
			/**
			 * coffee
			 */
			coffee: () => LocalizedString
			/**
			 * adventure
			 */
			adventure: () => LocalizedString
			/**
			 * trekking
			 */
			trek: () => LocalizedString
			/**
			 * ethnic
			 */
			ethnic: () => LocalizedString
			/**
			 * guide
			 */
			guide: () => LocalizedString
			/**
			 * transportation
			 */
			transport: () => LocalizedString
			/**
			 * translation
			 */
			translate: () => LocalizedString
		}
		/**
		 * I would like to ask for more information about {tour}... Please share the detailed itinerary and quote for our group.
		 */
		inquiry_template: (arg: { tour: unknown }) => LocalizedString
		err: {
			/**
			 * Please complete all fields
			 */
			form_all: () => LocalizedString
			/**
			 * Name must be at least 3 characters.
			 */
			form_name: () => LocalizedString
			/**
			 * Your email is invalid
			 */
			form_email: () => LocalizedString
			/**
			 * Your phone number is not valid
			 */
			form_phone: () => LocalizedString
			/**
			 * Languages must not be empty
			 */
			form_langs: () => LocalizedString
			/**
			 * Messages must not be empty
			 */
			form_msg: () => LocalizedString
			/**
			 * Failed to send message. Please try again!
			 */
			err_submit: () => LocalizedString
		}
		placeholder: {
			/**
			 * YOUR NAME *
			 */
			name: () => LocalizedString
			/**
			 * EMAIL *
			 */
			email: () => LocalizedString
			/**
			 * PHONE *
			 */
			phone: () => LocalizedString
			/**
			 * LANGUAGES *
			 */
			langs: () => LocalizedString
			/**
			 * MESSAGES *
			 */
			msg: () => LocalizedString
		}
	}
	about_page: {
		hero: {
			/**
			 * About Us — CHD Travel
			 */
			subtitle: () => LocalizedString
			/**
			 * Discover the Authentic Central Highlands with Local Explorers
			 */
			title: () => LocalizedString
			/**
			 * Born from a deep love for the red basalt soil and a passion to share the pristine beauty of the Central Highlands, CHD Travel pioneers authentic journeys, indigenous cultural immersion, and responsible, ethical tourism.
			 */
			desc: () => LocalizedString
			/**
			 * CHD Travel Philosophy
			 */
			philosophy_tag: () => LocalizedString
			/**
			 * "Go local — See local — Eat local"
			 */
			philosophy_quote: () => LocalizedString
			/**
			 * Travel is more than visiting a place — it is a genuine connection between people, wild nature, and the rhythmic heartbeat of indigenous villages.
			 */
			philosophy_desc: () => LocalizedString
		}
		difference: {
			/**
			 * What Sets CHD Travel Apart?
			 */
			title: () => LocalizedString
			/**
			 * Multilingual & Deep Insight
			 */
			pillar_1_title: () => LocalizedString
			/**
			 * Fluent in English and French, with deep understanding of international travel styles and indigenous ethnic heritage.
			 */
			pillar_1_desc: () => LocalizedString
			/**
			 * Tailor-Made & Flexible
			 */
			pillar_2_title: () => LocalizedString
			/**
			 * No rigid industrial packages. We handcraft and personalize each itinerary to suit your pace, fitness, and specific interests.
			 */
			pillar_2_desc: () => LocalizedString
			/**
			 * Ethical & Eco-Conscious
			 */
			pillar_3_title: () => LocalizedString
			/**
			 * Pioneering ethical wildlife interactions (elephant care over riding), organic coffee & cacao farm tours, and supporting local livelihood.
			 */
			pillar_3_desc: () => LocalizedString
		}
		team: {
			/**
			 * Founding Team & Tour Leaders
			 */
			title: () => LocalizedString
			/**
			 * Behind every memorable expedition is our dedicated founding trio — acclaimed by travelers worldwide on TripAdvisor for their passion, warmth, and expertise.
			 */
			subtitle: () => LocalizedString
			/**
			 * Founder & Managing Director
			 */
			member_1_role: () => LocalizedString
			/**
			 * Leading strategic vision and unique route design. His seamless bilingual fluency (EN/FR) and deep network with indigenous coffee growers bring profound cultural insight to every journey.
			 */
			member_1_desc: () => LocalizedString
			/**
			 * Corporate & Groups (B2B)
			 */
			member_1_tag: () => LocalizedString
			/**
			 * Co-Founder & French-Speaking Guide
			 */
			member_2_role: () => LocalizedString
			/**
			 * Highly acclaimed on TripAdvisor by international travelers. With boundless energy, wit, and encyclopedia-level local knowledge, he turns every trek, rafting trip, and village visit into an inspiring story.
			 */
			member_2_desc: () => LocalizedString
			/**
			 * French-Speaking Travelers (FIT)
			 */
			member_2_tag: () => LocalizedString
			/**
			 * Co-Founder & English-Speaking Guide
			 */
			member_3_role: () => LocalizedString
			/**
			 * The attentive "problem-solver" beloved for his heartfelt care and excellent English. Masterfully organizing logistics and leading unforgettable ethical elephant encounters around Lak Lake.
			 */
			member_3_desc: () => LocalizedString
			/**
			 * English-Speaking Travelers (FIT)
			 */
			member_3_tag: () => LocalizedString
		}
		legal: {
			/**
			 * Legal & Commitments
			 */
			subtitle: () => LocalizedString
			/**
			 * Transparent Licensing & Commitments
			 */
			title: () => LocalizedString
			/**
			 * Licensed Tour Operator
			 */
			commitment_1_title: () => LocalizedString
			/**
			 * Central Highlands Discovery Travel Co., Ltd is registered and operates in strict compliance with Vietnamese tourism law.
			 */
			commitment_1_desc: () => LocalizedString
			/**
			 * Comprehensive Travel Insurance & Safety
			 */
			commitment_2_title: () => LocalizedString
			/**
			 * All guests are protected by strict safety procedures and comprehensive travel insurance coverage.
			 */
			commitment_2_desc: () => LocalizedString
			/**
			 * Sustainable & Respectful Tourism
			 */
			commitment_3_title: () => LocalizedString
			/**
			 * Directly supporting indigenous ethnic communities and actively protecting natural ecology.
			 */
			commitment_3_desc: () => LocalizedString
			/**
			 * Registration Details
			 */
			reg_subtitle: () => LocalizedString
			/**
			 * Company Information
			 */
			reg_title: () => LocalizedString
			/**
			 * Company Name
			 */
			company_name_label: () => LocalizedString
			/**
			 * Công ty TNHH Dịch vụ Du lịch Khám phá Tây Nguyên
			 */
			company_name_vn: () => LocalizedString
			/**
			 * Central Highlands Discovery Travel Co., Ltd
			 */
			company_name_en: () => LocalizedString
			/**
			 * Business Registration No.
			 */
			tax_id_label: () => LocalizedString
			/**
			 * 6001577023
			 */
			tax_id: () => LocalizedString
			/**
			 * International Tour License
			 */
			license_label: () => LocalizedString
			/**
			 * 66-007/2017/TCDL-GP LHQT
			 */
			license_no: () => LocalizedString
			/**
			 * Management
			 */
			management_label: () => LocalizedString
			/**
			 * Mr Đức Lê (Director)
			 */
			management_val: () => LocalizedString
			/**
			 * Hotline
			 */
			hotline_label: () => LocalizedString
			/**
			 * 0913.471.352
			 */
			hotline_val: () => LocalizedString
			/**
			 * Email
			 */
			email_label: () => LocalizedString
			/**
			 * info@chdtravel.com
			 */
			email_val: () => LocalizedString
		}
		cta: {
			/**
			 * “With CHD Travel, you are not merely a visitor — you are a kindred companion joining us on an authentic and deeply inspiring journey into the heart of the Highlands.”
			 */
			quote: () => LocalizedString
			/**
			 * Reach out to our founding team for custom itineraries and personalized travel advice.
			 */
			desc: () => LocalizedString
			/**
			 * contact us
			 */
			btn: () => LocalizedString
		}
	}
	tours: {
		/**
		 * Joyful Journey: A Day to Remember
		 */
		intro_day: () => LocalizedString
		/**
		 * Multi-Day Highlands Tours: Stay longer. Go deeper
		 */
		intro_central: () => LocalizedString
		/**
		 * Dive into authentic local journeys! Whether you crave misty highlands, unhurried village immersion, or organic coffee farm walks, CHD Travel curates memorable encounters for every wanderlust.
		 */
		description: () => LocalizedString
		/**
		 * from
		 */
		price_from: () => LocalizedString
		/**
		 * Starting From
		 */
		price_starting_from: () => LocalizedString
		/**
		 * Featured & Best Seller
		 */
		featured_badge: () => LocalizedString
		/**
		 * View Details
		 */
		view_details: () => LocalizedString
		/**
		 * Book Now
		 */
		book_now_btn: () => LocalizedString
		/**
		 * Book Tour
		 */
		book_tour_btn: () => LocalizedString
		/**
		 * Relaxed
		 */
		pace_relaxed: () => LocalizedString
		/**
		 * Details
		 */
		click_detail: () => LocalizedString
		/**
		 * Back to tours
		 */
		back_to_tours: () => LocalizedString
		/**
		 * Plan this trip
		 */
		plan_trip: () => LocalizedString
		/**
		 * Book Now
		 */
		book_now: () => LocalizedString
		/**
		 * Plan your journey
		 */
		customize_trip: () => LocalizedString
		/**
		 * We curate private and personalized itineraries for you and your travel companions.
		 */
		customize_desc: () => LocalizedString
		trip_facts: {
			/**
			 * Trip Facts
			 */
			title: () => LocalizedString
			/**
			 * Route
			 */
			route: () => LocalizedString
			/**
			 * Duration
			 */
			duration: () => LocalizedString
			/**
			 * Style
			 */
			style: () => LocalizedString
			/**
			 * Private / Small Group
			 */
			style_val: () => LocalizedString
			/**
			 * Pacing
			 */
			difficulty: () => LocalizedString
			/**
			 * Easy / Mindful Walk
			 */
			difficulty_val: () => LocalizedString
			/**
			 * Departure
			 */
			departure: () => LocalizedString
			/**
			 * Buon Ma Thuot
			 */
			departure_val: () => LocalizedString
		}
		good_to_know: {
			/**
			 * Good to Know
			 */
			title: () => LocalizedString
			/**
			 * Best Season
			 */
			season_title: () => LocalizedString
			/**
			 * Dry season (Nov–Apr) brings sunny days and white coffee blossoms (Feb–Apr). Green season (May–Oct) showcases majestic cascading waterfalls.
			 */
			season_desc: () => LocalizedString
			/**
			 * What to Pack
			 */
			packing_title: () => LocalizedString
			/**
			 * Comfortable walking shoes, light jacket for cool highland evenings, sunscreen, eco insect repellent, and camera.
			 */
			packing_desc: () => LocalizedString
			/**
			 * Hotel Pickup
			 */
			pickup_title: () => LocalizedString
			/**
			 * Complimentary round-trip pickup from central Buon Ma Thuot hotels or BMT airport upon request.
			 */
			pickup_desc: () => LocalizedString
			/**
			 * Dietary Options
			 */
			diet_title: () => LocalizedString
			/**
			 * Special dietary requirements, vegetarian, and vegan options are warmly accommodated on all meals.
			 */
			diet_desc: () => LocalizedString
		}
		gallery: {
			/**
			 * 01 / Excursions
			 */
			excursions_subtitle: () => LocalizedString
			/**
			 * 02 / Grand Expeditions
			 */
			expeditions_subtitle: () => LocalizedString
			/**
			 * Unforgettable moments crafted into a single, enriching, unhurried day.
			 */
			day_desc: () => LocalizedString
			/**
			 * Multi-day mindful journeys through misty passes, ancient pine forests, and ethnic hamlets.
			 */
			central_desc: () => LocalizedString
			/**
			 * View all
			 */
			view_all: () => LocalizedString
			/**
			 * View all {count} photos
			 */
			view_all_photos: (arg: { count: unknown }) => LocalizedString
			/**
			 * Image gallery
			 */
			photos_aria: () => LocalizedString
			/**
			 * Previous photo
			 */
			prev_photo: () => LocalizedString
			/**
			 * Next photo
			 */
			next_photo: () => LocalizedString
			/**
			 * Close gallery
			 */
			close_gallery: () => LocalizedString
		}
		detail: {
			/**
			 * Tour Intro
			 */
			intro: () => LocalizedString
			/**
			 * Highlights
			 */
			highlights: () => LocalizedString
			/**
			 * Detailed Itinerary
			 */
			itinerary: () => LocalizedString
			/**
			 * Pricing Table
			 */
			price: () => LocalizedString
			/**
			 * Inclusions
			 */
			inclusion: () => LocalizedString
			/**
			 * Transportation, local guide, entrance tickets & bottled water included.
			 */
			inclusion_default: () => LocalizedString
			/**
			 * Departure
			 */
			departure_label: () => LocalizedString
			/**
			 * Duration
			 */
			duration_label: () => LocalizedString
			/**
			 * Group Size
			 */
			group_size_label: () => LocalizedString
			/**
			 * Close
			 */
			close: () => LocalizedString
			/**
			 * Number of guests
			 */
			pax_no: () => LocalizedString
			/**
			 * pax
			 */
			pax: () => LocalizedString
			/**
			 * Solo guest
			 */
			solo: () => LocalizedString
			/**
			 * Group of
			 */
			group: () => LocalizedString
			/**
			 * Book This Tour
			 */
			plan_this_trip: () => LocalizedString
			/**
			 * I'm interested in
			 */
			interested_in: () => LocalizedString
			/**
			 * When are you travelling?
			 */
			travelling_date: () => LocalizedString
			/**
			 * How many people?
			 */
			how_many_people: () => LocalizedString
			/**
			 * Anything you'd like us to know?
			 */
			notes_question: () => LocalizedString
			/**
			 * Dietary preferences, pickup points, or any special requests...
			 */
			notes_placeholder: () => LocalizedString
			/**
			 * Book Now
			 */
			send_enquiry: () => LocalizedString
			/**
			 * I'd like to book this tour
			 */
			enquiry_title: () => LocalizedString
			/**
			 * Guests
			 */
			stepper_guest_count: () => LocalizedString
			/**
			 * Unit Price
			 */
			stepper_unit_price: () => LocalizedString
			/**
			 * Total Price
			 */
			stepper_total_price: () => LocalizedString
			/**
			 * Contact for Price
			 */
			contact_for_price: () => LocalizedString
			/**
			 * Please contact CHD Travel for detailed customized pricing and personalized group consultation.
			 */
			contact_for_price_desc: () => LocalizedString
		}
	}
	blog_page: {
		/**
		 * chd journal
		 */
		title: () => LocalizedString
		/**
		 * stories & highland insights
		 */
		subtitle: () => LocalizedString
		/**
		 * Reflections from indigenous Highland journeys, ethnic village traditions, organic coffee harvests, and moments around the longhouse hearth.
		 */
		intro: () => LocalizedString
		/**
		 * all posts
		 */
		all_posts: () => LocalizedString
		/**
		 * highlights
		 */
		highlights: () => LocalizedString
		/**
		 * "Authentic moments and insights gathered from local Highland journeys."
		 */
		highlights_quote: () => LocalizedString
		/**
		 * read full post →
		 */
		read_full: () => LocalizedString
		/**
		 * read more →
		 */
		read_more: () => LocalizedString
		/**
		 * no articles available yet.
		 */
		no_posts: () => LocalizedString
		/**
		 * author:
		 */
		author_prefix: () => LocalizedString
		/**
		 * ← all articles
		 */
		all_articles_btn: () => LocalizedString
		/**
		 * View all
		 */
		view_all: () => LocalizedString
		/**
		 * View all {count} photos
		 */
		view_all_photos: (arg: { count: unknown }) => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * Featured
		 */
		featured_badge: () => LocalizedString
		categories: {
			/**
			 * all
			 */
			all: () => LocalizedString
			/**
			 * places
			 */
			places: () => LocalizedString
			/**
			 * food & coffee
			 */
			food: () => LocalizedString
			/**
			 * people
			 */
			people: () => LocalizedString
			/**
			 * stories
			 */
			stories: () => LocalizedString
			/**
			 * travel tips
			 */
			tips: () => LocalizedString
			/**
			 * events
			 */
			event: () => LocalizedString
			/**
			 * destinations
			 */
			destination: () => LocalizedString
			/**
			 * traveler stories
			 */
			story: () => LocalizedString
		}
	}
	seo: {
		/**
		 * Vietnam Highlands & Day Tours
		 */
		home: () => LocalizedString
		/**
		 * Day Tours
		 */
		day_tours: () => LocalizedString
		/**
		 * Highland Tours
		 */
		highland_tours: () => LocalizedString
		/**
		 * About Us
		 */
		about: () => LocalizedString
		/**
		 * Blog
		 */
		blog: () => LocalizedString
		/**
		 * Contact Us
		 */
		contact: () => LocalizedString
		/**
		 * Frequently Asked Questions
		 */
		faq: () => LocalizedString
		/**
		 * Terms of Service
		 */
		terms: () => LocalizedString
		/**
		 * Privacy Policy
		 */
		privacy: () => LocalizedString
	}
	error_page: {
		/**
		 * Service Temporarily Unavailable
		 */
		title_503: () => LocalizedString
		/**
		 * Page Not Found
		 */
		title_404: () => LocalizedString
		/**
		 * An error occurred
		 */
		title_default: () => LocalizedString
		/**
		 * We are experiencing temporary connection delays. Please refresh the page in a few moments.
		 */
		desc_503: () => LocalizedString
		/**
		 * The page you are looking for does not exist or has been moved.
		 */
		desc_404: () => LocalizedString
	}
	footer: {
		/**
		 * faq
		 */
		faq: () => LocalizedString
		/**
		 * terms of service
		 */
		terms: () => LocalizedString
		/**
		 * privacy policy
		 */
		privacy: () => LocalizedString
	}
	faq_page: {
		hero: {
			/**
			 * Help & Knowledge Base
			 */
			subtitle: () => LocalizedString
			/**
			 * Frequently Asked Questions
			 */
			title: () => LocalizedString
			/**
			 * Everything you need to know about booking, traveling, ethical wildlife guidelines, and exploring the Central Highlands with CHD Travel.
			 */
			desc: () => LocalizedString
		}
		categories: {
			/**
			 * All Questions
			 */
			all: () => LocalizedString
			/**
			 * Booking & Payment
			 */
			booking: () => LocalizedString
			/**
			 * Tours & Logistics
			 */
			tours: () => LocalizedString
			/**
			 * Elephant Ethics & Sustainability
			 */
			ethics: () => LocalizedString
			/**
			 * Preparation & Climate
			 */
			prep: () => LocalizedString
			/**
			 * Refunds & Policy
			 */
			cancellation: () => LocalizedString
		}
		items: {
			/**
			 * How do I book a tour with CHD Travel?
			 */
			q1: () => LocalizedString
			/**
			 * You can easily request a booking through our online booking modal on any tour page or via our Contact form. Our team will verify availability, send you a detailed personalized itinerary, and guide you through the payment steps within 24 hours.
			 */
			a1: () => LocalizedString
			/**
			 * What payment methods do you accept?
			 */
			q2: () => LocalizedString
			/**
			 * We accept bank transfers (VND for local accounts, USD/EUR via international SWIFT transfer), major credit/debit cards via secure online payment links, and cash upon arrival at our Buon Ma Thuot office.
			 */
			a2: () => LocalizedString
			/**
			 * Why does CHD Travel emphasize ethical elephant tourism?
			 */
			q3: () => LocalizedString
			/**
			 * We are committed to animal welfare. We do not support or conduct elephant riding. Instead, we offer ethical elephant observation and care experiences in Yok Don National Park and Lak Lake, allowing elephants to live naturally without exploitation or stress.
			 */
			a3: () => LocalizedString
			/**
			 * What is the best time of year to visit the Central Highlands?
			 */
			q4: () => LocalizedString
			/**
			 * The dry season from November to April offers ideal sunny weather, blooming wildflowers, and vibrant coffee blossom/harvest seasons (Nov–Feb). The green season from May to October brings dramatic waterfalls and lush tropical landscapes.
			 */
			a4: () => LocalizedString
			/**
			 * Are CHD Travel guides fluent in foreign languages?
			 */
			q5: () => LocalizedString
			/**
			 * Yes! Our tour leaders and co-founders are fluent in English and French, equipped with extensive regional knowledge, international storytelling experience, and deep connections with local ethnic minority communities (Ede, M’nong).
			 */
			a5: () => LocalizedString
			/**
			 * Can tours be customized for private groups or families?
			 */
			q6: () => LocalizedString
			/**
			 * Absolutely. We specialize in tailor-made itineraries tailored to your fitness level, travel dates, family needs, and special interests like specialty coffee, photography, or cultural ethnography.
			 */
			a6: () => LocalizedString
			/**
			 * What should I pack for highland trekking and excursions?
			 */
			q7: () => LocalizedString
			/**
			 * We recommend comfortable walking/hiking shoes, breathable cotton clothing, light layers for cool evenings, eco-friendly insect repellent, a hat, sun protection, and a refillable water bottle.
			 */
			a7: () => LocalizedString
			/**
			 * What is your cancellation and refund policy?
			 */
			q8: () => LocalizedString
			/**
			 * Cancellations made more than 7 days prior to departure receive a full refund minus minimal banking fees. Please review our Terms of Service for specific details on late cancellations and peak-season adjustments.
			 */
			a8: () => LocalizedString
		}
		cta: {
			/**
			 * Still have questions?
			 */
			title: () => LocalizedString
			/**
			 * Our local travel specialists are here to assist you with custom planning and advice.
			 */
			desc: () => LocalizedString
			/**
			 * contact our team
			 */
			btn: () => LocalizedString
		}
	}
	terms_page: {
		hero: {
			/**
			 * Legal Agreement
			 */
			subtitle: () => LocalizedString
			/**
			 * Terms of Service
			 */
			title: () => LocalizedString
			/**
			 * Please read these Terms of Service carefully before booking tours or utilizing services provided by Central Highlands Discovery Travel Co., Ltd (CHD Travel).
			 */
			desc: () => LocalizedString
		}
		sections: {
			/**
			 * 1. General Agreement & Tour Booking
			 */
			sec_1_title: () => LocalizedString
			/**
			 * By submitting a booking form, confirming an itinerary, or paying a deposit for any excursion organized by Central Highlands Discovery Travel Co., Ltd ("CHD Travel", "we", "us"), the client ("traveler", "you") agrees to be legally bound by these terms. A booking is confirmed once we issue a written confirmation voucher or formal invoice.
			 */
			sec_1_content: () => LocalizedString
			/**
			 * 2. Pricing, Deposits & Payment Terms
			 */
			sec_2_title: () => LocalizedString
			/**
			 * All tour prices are quoted in Vietnam Dong (VND) and estimated in US Dollars (USD) according to official reference exchange rates. A deposit of 30%–50% is required upon booking confirmation to secure private vehicles, permits, and licensed guides. The remaining balance must be settled prior to tour departure or upon arrival in Buon Ma Thuot as agreed.
			 */
			sec_2_content: () => LocalizedString
			/**
			 * 3. Cancellations & Refund Policy
			 */
			sec_3_title: () => LocalizedString
			/**
			 * If you need to cancel a booking, the following conditions apply: 
		• More than 7 days before departure: 100% refund of the paid amount (minus non-refundable bank transfer fees).
		• 3 to 7 days before departure: 50% refund of total tour value.
		• Less than 72 hours before departure or no-show: Non-refundable, as local community resources and logistics have been prepaid.
		In case of adverse weather or unforeseen official closures, CHD Travel will offer alternative dates, equivalent itineraries, or a fair prorated refund.
			 */
			sec_3_content: () => LocalizedString
			/**
			 * 4. Traveler Responsibilities & Safety Guidelines
			 */
			sec_4_title: () => LocalizedString
			/**
			 * Travelers are responsible for possessing valid travel documents, personal travel insurance, and declaring any health restrictions, allergies, or physical limitations prior to departure. Guests must respect local indigenous customs in ethnic minority villages (Ede, M’nong) and strictly comply with national park safety rules and ethical wildlife guidelines (no elephant riding or feeding unauthorized food).
			 */
			sec_4_content: () => LocalizedString
			/**
			 * 5. Force Majeure & Limitation of Liability
			 */
			sec_5_title: () => LocalizedString
			/**
			 * CHD Travel is not liable for itinerary changes, delays, or cancellations caused by acts of God, severe weather, natural disasters, epidemics, civil unrest, or governmental regulatory actions. In such circumstances, our team will do everything reasonably possible to provide suitable alternatives and safeguard your security.
			 */
			sec_5_content: () => LocalizedString
			/**
			 * 6. Governing Law & Dispute Resolution
			 */
			sec_6_title: () => LocalizedString
			/**
			 * These terms and any disputes arising from our services are governed by and construed in accordance with the laws of the Socialist Republic of Vietnam. Any unresolved dispute shall be submitted to the competent commercial court in Dak Lak Province, Vietnam.
			 */
			sec_6_content: () => LocalizedString
		}
	}
	privacy_page: {
		hero: {
			/**
			 * Data Protection & Transparency
			 */
			subtitle: () => LocalizedString
			/**
			 * Privacy Policy
			 */
			title: () => LocalizedString
			/**
			 * CHD Travel is dedicated to safeguarding your privacy and ensuring your personal information is collected, processed, and maintained securely and transparently.
			 */
			desc: () => LocalizedString
		}
		sections: {
			/**
			 * 1. Information We Collect
			 */
			sec_1_title: () => LocalizedString
			/**
			 * When you interact with our website or book a tour, we may collect:
		• Contact details: Full name, email address, phone/WhatsApp number, nationality.
		• Booking specifics: Travel dates, group size, special dietary needs, or physical accessibility requirements.
		• Travel permit data: Passport number and date of birth when strictly necessary for National Park entry permits or local authority registrations in border/highland zones.
			 */
			sec_1_content: () => LocalizedString
			/**
			 * 2. How We Use Your Information
			 */
			sec_2_title: () => LocalizedString
			/**
			 * We use your personal information solely to:
		• Process tour reservations and provide customized itinerary planning.
		• Send automated booking confirmations, vouchers, and essential travel updates.
		• Comply with Vietnamese legal requirements, including hotel guest registration and national park visitor permits.
		• Enhance website performance and user experience (e.g. remembering your preferred language).
			 */
			sec_2_content: () => LocalizedString
			/**
			 * 3. Data Security & Anti-Spam Protection
			 */
			sec_3_title: () => LocalizedString
			/**
			 * We employ industry-standard security practices to protect your data against unauthorized access, loss, or misuse. Our website utilizes SSL encryption, rate limiting, and honeypot security mechanisms on all submission forms. We never sell, rent, or trade your personal information to third-party marketers.
			 */
			sec_3_content: () => LocalizedString
			/**
			 * 4. Third-Party Disclosures & Partners
			 */
			sec_4_title: () => LocalizedString
			/**
			 * We only share relevant minimal details with trusted service partners directly involved in your journey (e.g., licensed local drivers, eco-homestay hosts, and national park rangers for permit issuance). All partners are bound to handle your data confidentially and solely for operational purposes.
			 */
			sec_4_content: () => LocalizedString
			/**
			 * 5. Cookies & Browser Storage
			 */
			sec_5_title: () => LocalizedString
			/**
			 * Our website uses essential lightweight cookies and local storage exclusively for core functionality — such as remembering your selected locale (EN/VI/FR) and temporarily caching currency exchange rates to optimize page load speeds. We do not run invasive tracking or third-party behavioral advertising cookies.
			 */
			sec_5_content: () => LocalizedString
			/**
			 * 6. Your Rights & Contact Details
			 */
			sec_6_title: () => LocalizedString
			/**
			 * You have the right to request access to the personal data we hold about you, request corrections, or request deletion once legal retention periods for tax and licensing have expired. To exercise these rights, please email us at info@chdtravel.com.
			 */
			sec_6_content: () => LocalizedString
		}
	}
}

export type Formatters = {}
